### ISSUE TITLE
blocking issue: mathcomp.dev currently does not builds with coq.dev

### ISSUE THREAD

**Issue by erikmd** [math-comp/math-comp#1034]
cf. https://gitlab.inria.fr/math-comp/math-comp/-/jobs/3189383

This is a blocking issue because no mathcomp.dev images for coq.* will be pushed by gitlab ci to https://hub.docker.com/r/mathcomp/mathcomp-dev if not all the three versions `coq-{8.16,8.17,dev}` build from source

@proux01 can you take a look at this?

**Comment by proux01** [comment]
The solution would be to merge https://github.com/proux01/hierarchy-builder/tree/coq-master into https://github.com/math-comp/hierarchy-builder/tree/coq-master (cc @gares ) which should work as it is tested in CI.
Could we disactivate dev as a short term solution?

**Comment by erikmd** [comment]
but in the longer term, I think it's really important to ensure that mathcomp master is tested against the latest coq-dev (even if mathcomp can be tested in coq CI), notably because of the dedicated tests that had been added a few releases before by @gares' PR: https://github.com/math-comp/math-comp/pull/433/files
