### ISSUE TITLE
math-comp 2.0.0 failed to build

### ISSUE THREAD

**Issue by chenrui333** [math-comp/math-comp#1050]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  COQC ssreflect/eqtype.v
  File "./ssreflect/eqtype.v", line 3, characters 0-34:
  Error: Cannot find a physical path bound to logical path
  structures with prefix HB.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5577167438/jobs/10189632565
relates to Homebrew/homebrew-core#130643

**Comment by chenrui333** [comment]
Does it need ocaml 5.0.0 to build?

**Comment by affeldt-aist** [comment]
No, it does not. But it requires coq-hierarchy-builder >= 1.4.0 (see https://github.com/math-comp/math-comp/blob/master/coq-mathcomp-ssreflect.opam for dependencies).

**Comment by affeldt-aist** [comment]
@chenrui333 We interpret your thumb up as the fact that you resolved your issue. Please, reopen if needed.
