### ISSUE TITLE
Implicit arguments of `natr1`

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/math-comp#1064]
https://github.com/math-comp/math-comp/blob/0eec052f6c8a3b3d0bfb22c2a1ca3ae2aba1d0fd/mathcomp/algebra/ssralg.v#L998

With MathComp 1.16, `R` is not an implicit arguments, if this is still the case with more recent versions, we could consider making it implicit.

**Comment by proux01** [comment]
@affeldt-aist I can confirm this is still the case on master
