### ISSUE TITLE
Windows installers (32-bit and 64-bit) for mathcomp under Coq 8.6 ?

### ISSUE THREAD

**Issue by mihai303** [math-comp/math-comp#109]
When will there be Windows installers (32-bit and 64-bit) for mathcomp under Coq 8.6 ?

**Comment by andrew-appel** [comment]
+1 (Appel)
+1 (Beringer)

**Comment by gares** [comment]
Sorry for delay, they are online now:   http://math-comp.github.io/math-comp/

Unfortunately my key has expired, so windows will complain the software is unsigned.
