### ISSUE TITLE
Missing result on seq.uniq ?

### ISSUE THREAD

**Issue by strub** [math-comp/math-comp#112]
Hi,

I've been quite surprised not to be able to derive the following result with the current state of the `seq` library. Am i missing something or should i do a pull request?

```
Lemma uniqPn {T : eqType} (x0 : T) (s : seq T) : ~~ uniq s ->
  exists i, exists j,
    [&& i < size s, j < size s, i != j & nth x0 s i == nth x0 s j].
Proof.
elim: s => //= x s ih /nandP[]; last first.
+ by case/ih=> [i] [j] {ih}ih; exists i.+1, j.+1.
rewrite negbK => /(nthP x0) [j ltj <-].
by exists 0, j.+1 => /=; rewrite eqxx andbT.
Qed.

```

**Comment by ejgallego** [comment]
Indeed, at some point I also had this abdomination:

```
Lemma uniqP {T : eqType} (x0 : T) (s : seq T) :
  reflect (forall i j, i < size s -> j < size s ->
                       [|| i == j | nth x0 s i != nth x0 s j]) (uniq s).
Proof.
elim: s => [|x s /= [hu|huN]]; first by left; case.
+ case: (_ \in _) / boolP => /(nthP x0) hmem; constructor.
  - move=> neq; case: hmem => idx1 hs hnth.
  - by have := neq idx1.+1 0 hs erefl; rewrite /= hnth eqxx.
  case=> [|i] [|j] hsi hsj //=; last exact: hu.
  - by case: eqP => // hs; case: hmem; exists j.
  by case: eqP => // hs; case: hmem; exists i.
rewrite andbF; constructor => hu; apply: huN => i j hsi hsj.
by have := hu i.+1 j.+1 hsi hsj.
Qed.
```
from which is however a bit inconvenient to derive your fact.

**Comment by CohenCyril** [comment]
Hi,

This is quite direct with tuples by negation of boolean injectivity on ordinals (but difficult to find I guess), but a bit longer with lists... Maybe it should be integrated.

```
Lemma uniq_tupleP {T : eqType} {n : nat} {t : n.-tuple T} :
  reflect (injective (tnth t)) (uniq t).
Proof. by rewrite [t in X in reflect _ X]tuple_map_ord; apply: injectiveP. Qed.

Lemma uniq_tuplePn {T : eqType} {n : nat} {t : n.-tuple T} :
  reflect (exists i, exists2 j, i != j & tnth t i = tnth t j) (~~ uniq t).
Proof. by rewrite [t in X in reflect _ X]tuple_map_ord; apply: injectivePn. Qed.

Lemma uniqPn {T : eqType} (x0 : T) (s : seq T) :
  reflect (exists i j, [&& i < size s, j < size s,
                        i != j & nth x0 s i == nth x0 s j])
          (~~ uniq s).
Proof.
set n := size s; rewrite -[s]/(val (in_tuple s)).
move: (in_tuple s); rewrite -/n; move: n => n t /=.
apply: (iffP uniq_tuplePn) => [[i [j neq_ij eq_nij]]|[i [j]]].
  by exists i, j; rewrite !ltn_ord neq_ij /= -!tnth_nth eq_nij.
move=> /and4P [i_n j_n neqij /eqP nij].
by exists (Ordinal i_n), (Ordinal j_n); rewrite -?val_eqE // !(tnth_nth x0).
Qed.

```
Best,

**Comment by CohenCyril** [comment]
uniqP is also a bit difficult to get...
```
Lemma uniqP {T : eqType} (x0 : T) (s : seq T) :
 reflect {in [pred i | i < size s] &, injective (nth x0 s)} (uniq s).
Proof.
pose o := @Ordinal (size s); set n := size s; rewrite -[s]/(val (in_tuple s)).
apply: (iffP uniq_tupleP)=> [tnth_inj i j iP jP|nth_inj i j]; last first.
  by rewrite !(tnth_nth x0) => /nth_inj/val_inj; apply; apply: ltn_ord.
by rewrite -[i]/(val (o i iP)) -[j]/(val (o j jP)) -!tnth_nth => /tnth_inj ->.
Qed.
```

**Comment by strub** [comment]
I was expecting something in the lines of what you wrote, using
injectivity, but forgot tuple_map_ord. Anyway, IMO, these results should be
integrated.

Le mer. 8 mars 2017 à 19:54, Cyril Cohen <notifications@github.com> a
écrit :

**Comment by CohenCyril** [comment]
For the two lemmas on tuple, I think they could be integrated as such. But for the seq ones, I'm not sure which phrasing is best though (ordinal vs predicate i < n). For uniqPn I think the best is an ordinal formulation (because no one expect to use the view from right to left, whether in a conclusion or hypothesis), but fot uniqP the view might be used in both direction, so the domain of the injectivity is subject to debate...

**Comment by strub** [comment]
Note that you cannot really use `uniq_tupleP` in `uniqP`. You have some kind of dependency issue. I'm going to try a push a PR today from your remarks.

**Comment by CohenCyril** [comment]
@strub did you read correctly uniq_tupleP?

**Comment by strub** [comment]
@CohenCyril Yes. What do you want me to read instead ? :)

**Comment by strub** [comment]
I think I understood what you want to say. My dependency remark was at top-level: you have to push `uniqP(n)` in `tuple.v` with your proofs (it is using `uniq_tupleP(n)`)

**Comment by CohenCyril** [comment]
Ah ok, it's kind of a shame not to take advantage of it though...
Also I think the following formulation is slightly better...
`Lemma uniqPn {T : eqType} (x0 : T) (s : seq T) :
  reflect (exists i j : 'I_(size s),  i != j /\ nth x0 s i = nth x0 s j)  (~~ uniq s).`

**Comment by strub** [comment]
@CohenCyril I agree with you, but I don't see any good solution. Regarding the formulation, I took the one closest to `nth_uniq` (i.e. using `nat` and pre-condition), but I don't have any strong opinion about that.
