### ISSUE TITLE
`fun_scope` and `function_scope`

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#1130]
MathComp uses [`fun_scope`](https://github.com/coq/coq/blob/1788628756921f2b3684023ec7f0628a53ac0b26/theories/ssr/ssrfun.v#L390) as the notation scope for functions. However, the Coq standard library declares [`function_scope`](https://github.com/coq/coq/blob/1788628756921f2b3684023ec7f0628a53ac0b26/theories/Init/Notations.v#L122) for the same purpose, as I noticed in #978.

Since there is no declaration `Bind Scope fun_scope with Funclass.` in MathComp, the use of `fun_scope` and `function_scope` are actually mixed in MathComp, e.g.,
```coq
About seq.map.
```
```
map : forall {T1 T2 : Type}, (T1 -> T2) -> seq T1 -> seq T2

map is not universe polymorphic
Arguments map {T1 T2}%type_scope f%function_scope s%seq_scope
                                  ^^^^^^^^^^^^^^^
map is transparent
Expands to: Constant mathcomp.ssreflect.seq.map
```

The best solution would be to unify these two notation scopes. However, I'm unsure if we can provide reasonable transition/deprecation steps since `Notation fun_scope := function_scope.` does not work. Shouldn't we at least declare `Bind Scope fun_scope with Funclass.` in `ssrfun.v`?

**Comment by pi8027** [comment]
@CohenCyril There is an issue with that transition. Coq does not allow us to declare several scope delimiters for one notation scope. So, by doing:
```
Delimit Scope function_scope with fun_scope.
```
we get:
```
Warning: Overwriting previous delimiting key function in scope function_scope
[overwriting-delimiting-key,parsing,default]
```
and there is no way to simulate:
```
Delimit Scope fun_scope with FUN.
```
declared in `ssrfun.v`.

**Comment by proux01** [comment]
I would be in favor of simply removing fun_scope and telling everyone in changelog to do `sed ...` to change all occurences of `fun_scope` to `function_scope`. For `FUN`, it seems almost unused (only found three dozen occurences in analysis and some HB example) so just removing it looks fine.

**Comment by pi8027** [comment]
Ok, I will redo #1131 to replace `fun_scope` with `function_scope`.

**Comment by proux01** [comment]
@pi8027 about `%FUN`, note that we can perfectly do `Delimit Scope function_scope with FUN` just like we do `Delimit nat_scope with N`. This only triggers a warning but then `%function` and `%FUN` can be used interchangeably.
