### ISSUE TITLE
Check MC1 backports

### ISSUE THREAD

**Issue by proux01** [math-comp/math-comp#1154]
Check the TODO: MC1 label and backport missing PRs.

**Comment by pi8027** [comment]
Do we need to continue backporting stuff from MC2 to MC1 now? [Trajectories](https://github.com/math-comp/trajectories) is probably the only active project still depending on MC1. Asking the MC users this question tomorrow is also an option.

**Comment by proux01** [comment]
I'd personally stop backporting anything and declare 1.19.0 the last MC1 release, but indeed, let's discuss that together.
