### ISSUE TITLE
Mono in partial order morphisms

### ISSUE THREAD

**Issue by zstone1** [math-comp/math-comp#1170]
Something came up in the last mathcomp analysis meeting regarding `homo` vs `mono` in Order.v. 

For a function `f` between partial orders, saying `{mono f : x y / x<= y}` indicates that if `f(x)` and `f(y)` are comparable, so are `x` and `y`. In particular, a function from a non-total to a total order can't be `{mono f : x y / x<= y}`. Surprising, but maybe useful sometimes.

What surprised me more is that this is the definition of `order_morphism`. Was it intentional for there to be no order morphisms from a non-trivial powerset lattice to a 1 point lattice? I would have expected `homo` instead.

**Comment by CohenCyril** [comment]
@zstone1 thanks for pointing that out.
https://github.com/math-comp/math-comp/blob/677ddcff9174fb24eb1089246b211d36c78b7256/mathcomp/ssreflect/order.v#L4958-L4959
 The definition of order morphism is indeed broken as even in the case of total order it imposes that the morphism is a mono. It must be updated to `{homo f : x y / x <= y}`

**Comment by CohenCyril** [comment]
@proux01 could we safely assume that this definition has not been used anywhere yet? Otherwise we need to consider a two-phase deprecation process (step 2. rename and deprecate the old name, have the right notion with a different name. step 2. rename the right notion with the original name)

**Comment by proux01** [comment]
I'm probably the one who made the mistake. Order morphism where inspired by ring morphisms (in ssralg.v) and my goal was only to be able to transport order structures to subtypes. With all the work during the porting to hierarchy-builder, it probably didn't receive enough attention. So indeed I wouldn't be surprised if there is (a lot of) room for improvement here.

> could we safely assume that this definition has not been used anywhere yet

No, it's used in dioid (for instance https://github.com/math-comp/dioid/blob/cf0cafea45c700230d97ddd9342baa1479a0c522/complete_lattice.v#L458 ), which I should probably add to CI. However it's only in master and I haven't released it, so I'm fine with skipping the deprecation process.

**Comment by CohenCyril** [comment]
> With all the work during the porting to hierarchy-builder, it probably didn't receive enough attention.

Indeed, I accidentally discovered the existence of this structure last week, so I probably didn't pay enough attention to this addition, mea culpa.

> However it's only in master and I haven't released it, so I'm fine with skipping the deprecation process.

Thanks that would be very helpful.

**Comment by affeldt-aist** [comment]
iiuc, we need to keep the current `order_morphism` under a different name?

**Comment by proux01** [comment]
Probably. I wonder whether we are not mixing two things (but maybe they are closely related) : monotonic functions (usually non strictly monotonic) and substructures for the order hierarchy (which require strict monotonicity ?).

**Comment by CohenCyril** [comment]
substructure require strict monotonicity but it's "accidental", it happens to be non strict + injective
