### ISSUE TITLE
Importing Num.Def disables notation `|_|` for `Num.norm _`

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#1188]
Indeed:

```coq
From mathcomp Require Import all_ssreflect all_algebra.

Check (Num.norm _). (* displays `|_| *)

Import Num.Def.

Check (Num.norm _). (* displays (normr _) *)
```

**Comment by proux01** [comment]
I guess the abbreviation should be parsing only https://github.com/math-comp/math-comp/blob/2aeffe031c001422a8d91a282d71e1ed01d2ab91/mathcomp/algebra/ssrnum.v#L188
could you open a PR please?
