### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by xamgore** [math-comp/math-comp#122]
Hi there! I want to compile math-comp (git clone this repo, cd mathcomp, make), but get an error:

```bash
CAMLOPT -pack -o ssreflect_plugin.cmx
CAMLOPT -shared -o ssreflect_plugin.cmxs
COQC ssreflect/ssreflect.v
File "./ssreflect/ssreflect.v", line 5, characters 0-37:
Error: while loading
/home/osboxes/Downloads/math-comp/mathcomp/ssreflect_plugin.cmxs:
implementation mismatch on Unix
make[1]: *** [Makefile.coq:592: ssreflect/ssreflect.vo] Error 1
make: *** [Makefile:26: all] Error 2
```

```bash
$ coqc -v
The Coq Proof Assistant, version 8.6 (February 2017)
compiled on Feb 22 2017 19:37:17 with OCaml 4.04.0
```

```bash
$ make -v
GNU Make 4.2.1 Built for x86_64-unknown-linux-gnu
```

Same when installing from AUR (arch user repository). Can you do smth with it?

**Comment by ejgallego** [comment]
What do `ocamlc -v` , `which coqc` , `which coq_makefile` say?

**Comment by xamgore** [comment]
```bash
$ ocamlc -v
The OCaml compiler, version 4.04.1
Standard library directory: /usr/lib/ocaml
```

```bash
$ which coqc
/usr/bin/coqc
```

```bash
$ which coq_makefile
/usr/bin/coq_makefile
```

**Comment by ejgallego** [comment]
Here you have it, to compile math-comp, you must use the same compiler used to compile Coq.

**Comment by xamgore** [comment]
Ok. I tried to install coq from sources (with campl5 dependency), and loaded math-comp. Got the error:

```
CAMLC -pp -c ssreflect.ml4
findlib: [WARNING] cannot read directory /dev/null: Not a directory
Redundant [TYPED AS] clause in [ARGUMENT EXTEND ssrindex].
File "ssreflect.ml4", line 670, characters 21-26:
Error: Unbound module Gramext
Hint: Did you mean Gram?
make[1]: *** [Makefile.coq:560: ssreflect.cmo] Error 2
make: *** [Makefile:26: all] Error 2
```

Google says that another guys has [faced with the same error](https://github.com/NixOS/nixpkgs/issues/14829#issuecomment-274940986), but they do smth strange :)

```
$ coqc -v
The Coq Proof Assistant, version 8.6 (May 2017)
compiled on May 16 2017 19:46:58 with OCaml 4.04.1

$ ocamlc -v
The OCaml compiler, version 4.04.1
Standard library directory: /usr/lib/ocaml

$ which coq_makefile
/usr/local/bin/coq_makefile
```

Seems that either coq isn't very user-friendly or I have both left hands.

**Comment by ejgallego** [comment]
uh... this is looking ugly; where did you got your ocaml and camlp5 for? Which distro are you using. What does `ocamlfind list | grep campl5` say?

I thoroughly recommend opam these days if you can. Contrary to `/usr/local/` installs, it will keep your ocaml toolchain consistent, which unfortunately is quite delicate in that aspect.

**Comment by xamgore** [comment]
I have manjaro (arch based) distro, ocaml & camlp5 were got through pacman, `ocamlfind list | grep campl5` displays nothing. 

Actually I'm not familiar with ocaml ecosystem, but will try.

> The instructions assume you are in the mathcomp directory and that you have OPAM installed and __configured with the standard Coq repositories__.

What does the last one mean, how can I configure it?

**Comment by ejgallego** [comment]
Yeah for some reason your manajo distro misconfigured ocamlfind. I recommend you remove the pacman ocaml stuff but for OPAM, and work with that, you will have a much more pleasant experience.

Regarding Coq and OPAM, you are missing the Coq repository. I recommend you follow my instructions below as every other site is either out of date or misses steps:

```
# Let's remove the opam switches for a start
rm -rf ~/.opam
opam init --compiler=4.04.1
opam repo add coq-released http://coq.inria.fr/opam/released
opam update
opam install coq-mathcomp-ssreflect
```

**Comment by xamgore** [comment]
Hm. Suddenly have found a link http://math-comp.github.io/math-comp/, just downloaded binaries for windows — you should definitely attach it to the repository, above: 

![image](https://cloud.githubusercontent.com/assets/4586392/26151740/bf270b92-3b0c-11e7-9cd5-5b6e5c1690dc.png)

It would be nice if there was a page with instruction, how to build and install coq + ssreflect, using ocaml/opam for example.

Thank you very much for help! 👍

**Comment by ejgallego** [comment]
Would be great if you could open a ticket with the information that needs to be added in the webpage, thanks!
