### ISSUE TITLE
ssreflect Windows installer for Coq 8.6.1

### ISSUE THREAD

**Issue by andrew-appel** [math-comp/math-comp#135]
Will there be a Windows installer for math-comp, compatible with Coq 8.6.1 (32 bit, and 64 bit) ?

**Comment by gares** [comment]
Thanks for the heads up, I'm on VAC but I think I can give it a try next WE.

Best,

**Comment by gares** [comment]
done: http://math-comp.github.io/math-comp/ (reload the page)

**Comment by gares** [comment]
Oh, BTW, the ssreflect plugin (along with a few .v files) was merged in Coq 8.7, so this kind of issue will be soon over!
