### ISSUE TITLE
Math-comp 1.7 ?

### ISSUE THREAD

**Issue by ejgallego** [math-comp/math-comp#137]
Dear Math-Comp devs,

what is the plan for 1.7 ?

I am asking as in particular we would like to use some of the changes done by Cyril in the `algC / closedField` interface, however these updates are not available in OPAM, so users have a bit of pain trying to use that.

Cheers, E.

**Comment by ejgallego** [comment]
IMVVHO, another thing that could also make sense is to release a 1.7 that requires Coq 8.7; this would allow to cleanup all the complex machinery for conditional compilation present these days.

I think Coq's CI should be good enough against compatibility problems, even if unfortunately it doesn't test the last top files preceding `odd_order`.

**Comment by ejgallego** [comment]
c.f. #132

**Comment by gares** [comment]
I close this, since 1.7 is released
