### ISSUE TITLE
provide all2

### ISSUE THREAD

**Issue by bgregoir** [math-comp/math-comp#156]
The function all2 on list is not present in ssr.
We proving relation over programs, this is the kind of predicate which is very useful.
It can be easily defined either by a fixpoint or using all, zip, and size. 
Both solution have advantage it is not my point.
But it is a little bit boring to redefine it (and it associated lemma) 
each time I start a new development.

**Comment by CohenCyril** [comment]
Please consider making a pull request, we can then work towards the best version to integrate.

**Comment by CohenCyril** [comment]
@bgregoir I understand you have several copies of this, can you make a little syntesis either here or as a pull request? Cheers ;)

**Comment by strub** [comment]
I took one of the several copies and pushed it. Now, I'm not sure which lemmas we may want to import.
