### ISSUE TITLE
[rewrite foo in hyp] changes order of hypotheses

### ISSUE THREAD

**Issue by robbertkrebbers** [math-comp/math-comp#17]
For example:
```
Require Import mathcomp.ssreflect.ssreflect.
Require Import Morphisms Setoid.

Lemma test1 (P : nat -> Prop) x y : P x -> x = y -> True.
Proof.
  intros H1 H2.
  rewrite H2 in H1.
  (* flips the order of H1 and H2 *)
  Restart.
  intros H1 H2.
  rewrite ->H2 in H1.
  (* does not flip the order *)
Admitted.
```
This is purely aesthetic, but in the case of proofs with many hypotheses one can easily loose track if the order starts to change arbitrarily.

**Comment by gares** [comment]
Comment by Georges

    It's not obvious to insert introduced definitions in their original positions
    in the context which <tactic> can modify: using "set " to abbreviate
    subexpressions is common enough, and forces all introductions to occur at the
    end (or after the set); even plain rewrite can insert assumption or constants
    that are lower in the context. We could just try our best, at the expense of
    underspecifying "in", but I must say that I've often found the current behaviour
    quite useful in large proofs, as it prevents the assumption(s) you are working
    on from scrolling out of view.
