### ISSUE TITLE
Please add extras and ssrreals

### ISSUE THREAD

**Issue by ejgallego** [math-comp/math-comp#173]
Hi all, as a follow up to the discussion I think the library could ship a few extra files that would make life easier for users, in particular beginners.

Here, the definition of "extra" is close to "not needed in the main proof", but of course, that's quite subjective. The first such extra file that could go in `algebra` is the `ssrreals` [or however it is called], providing all the instances of the hierarchy for Coq's `R`.

IMVHO is is a bit frustrating for the library not to work with Coq reals, and while I understand that `ssreals` is not the proper solution for researchers, its absence makes trouble. Stealing an example from a new user today:

```coq
Definition mean  (S: {fset R}) :=  1 %/ #|S| * (\sum_(s: S) s).
``` 

which of course failed with the cryptic message:
```
Error:
The term "Phant R" has type "phant R" while it is expected to have type "phant ?K".
```
IMVHO, her experience would have been much better if `R` [here Coq's reals] would have worked out of the box after the proper imports.

[Yup, I know there are other problems in the above definition regarding types, but I just copied the try verbatim as I think it is interesting]

**Comment by erikmd** [comment]
Hi @ejgallego, I join the discussion because I have several Coq developments that rely on both math-comp and (classical) reals, I'm also very interested in the problem you raise. A few comments:

> Here, the definition of "extra" is close to "not needed in the main proof", but of course, that's quite subjective. The first such extra file that could go in algebra is the ssrreals [or however it is called], providing all the instances of the hierarchy for Coq's R.

Actually it is easy to show that `Coq.Reals.Rdefinitions.R` has an `eqType` structure, without requiring anything more than the `Reals` from stdlib.
But if you want to put some `choiceType` structure on `R`, this axiomatics is not sufficient...
This explains why the support for stdlib's `Reals` cannot be easily bundled in mathcomp.
A few years ago, Ioana Pasca, Micaela Mayero, Laurence Rideau, Laurent Théry, and I had written a file `Rstruct.v` to instantiate the whole `ssralg` hierarchy for `R` (up to `realFieldType`).
FYI the latest version of [this Rstruct.v file is on that forge](https://sourcesup.renater.fr/plugins/scmgit/cgip-bin/gitweb.cgi?p=validsdp.git;a=blob_plain;f=theories/Rstruct.v;hb=HEAD).
(However this solution is not fully satisfactory, because of the required axioms.)

Also @ejgallego, have you heard from the work by @strub and @amahboubi to develop [an alternate coq/ssreflect library for reals](https://github.com/strub/coq-alternate-reals)?

**Comment by ejgallego** [comment]
Hi @erikmd ; thanks for your comments, indeed I am aware of the new reals development and of the `Rstruct` file of which there are many versions floating around. I'm also aware of the extra axioms needed [TTBOMK these should be consistent with Coq].

Let me make the point clearer, I am not asking to make this file to be part of `math-comp`, but instead of an "extras" package that is distributed with math-comp and contains useful things or hacks. It would be great if we could stop everyone having its own version of this file.

I think I don't exaggerate when I say I had to point out to this file to at least 20 distinct users who where asking in different forums why math-comp couldn't be used with reals. At some point even one user had lost a couple of days reimplementing all the instances themselves!

**Comment by erikmd** [comment]
Hi @ejgallego
> Let me make the point clearer, I am not asking to make this file to be part of math-comp, but instead of an "extras" package that is distributed with math-comp and contains useful things or hacks. It would be great if we could stop everyone having its own version of this file.

OK I see your point! having one such "mathcomp-extra" lib (possibly split in several opam packages?) would be useful to gather in a single place commonly used mathcomp-based material, that can't be part of mathcomp's core...

**Comment by ejgallego** [comment]
Yup, that's kind of the point. Of course all this seems a bit fuzzy, maybe I just submit a PR adding the actual file :)

It just happened that today another person asked for the real instances, and I thought it would be good to open an issue so we don't forget.

By the way @ all devs? Is the file @erikmd points to the most up to date one?

**Comment by CohenCyril** [comment]
this is the latest version of the file https://github.com/CohenCyril/cara/blob/master/Rstruct.v. but it relies on some extra classical + extensionality axioms. So it is not a strict progression (see Sophie Bernard version for the most advanced one without extra axioms compares to the original one).

I am not convinced that this extra ssrreals package should be provided in the repository mathcomp. The point beiing that until coq-alternate-reals ans cara there were no canonical way to do reals with mathcomp and *without* any theorem from the standard library.

I think the question should rather be: what sould I import if I want to mathcomp on R? And for me the answer is : let's package and install these two new devlopments under coq-mathcomp-reals (or coq-mathcomp-classical or anything meaningful). But no need for them to be part of the mathcomp repo (maybe the mathcomp organization).

**Comment by erikmd** [comment]
Hi @CohenCyril; I was not aware of the [cara](https://github.com/CohenCyril/cara) library, thanks for the pointer.
> see Sophie Bernard version for the most advanced one without extra axioms compares to the original one

Do you speak about https://github.com/Sobernard/Struct/blob/master/Rstruct.v ? it seems to use the same axioms as https://github.com/CohenCyril/cara/blob/master/Rstruct.v .

> until coq-alternate-reals ans cara there were no canonical way to do reals with mathcomp and *without* any theorem from the standard library.
> I think the question should rather be: what sould I import if I want to mathcomp on R? And for me the answer is : let's package and install these two new devlopments under coq-mathcomp-reals (or coq-mathcomp-classical or anything meaningful). But no need for them to be part of the mathcomp repo

👍

**Comment by ejgallego** [comment]
Maybe just having the pointers in the FAQ/doc is enough, math-comp "extra" could be well a wiki page / tar. gz. indeed.

**Comment by CohenCyril** [comment]
> Do you speak about https://github.com/Sobernard/Struct/blob/master/Rstruct.v ? it seems to use the same axioms as https://github.com/CohenCyril/cara/blob/master/Rstruct.v .

Yes that's what I'm talking about. cara's Rstruct additionally imports boolp.v from coq-alternate-reals which relies on forall P, {P} + {~ P}

**Comment by CohenCyril** [comment]
The answer to this question is now http://github.com/math-comp/analysis.
