### ISSUE TITLE
[rewrite] does not work with partial orders

### ISSUE THREAD

**Issue by robbertkrebbers** [math-comp/math-comp#18]
Coq's `rewrite` tactic supports rewriting with partial orders, but in case of ssr's `rewrite` tactic this does not seem to work. For example:

```
Require Import Arith NPeano.
Require Import mathcomp.ssreflect.ssreflect.

Lemma foo x y z : x <= y -> y <= z -> x <= z.
Proof.
  move=> H1 H2.
  Fail rewrite H1.
  (* Error: not a rewritable relation: (le x y) in rule H1 *)
  rewrite ->H1.
Admitted.
```

**Comment by robbertkrebbers** [comment]
If I add the following to the file:
```
Instance: Coq.Classes.RelationClasses.RewriteRelation le.
```
then the `rewrite` goes through.

**Comment by gares** [comment]
https://coq.inria.fr/bugs/show_bug.cgi?id=4549

**Comment by robbertkrebbers** [comment]
This problem became considerably worse in 8.6, see https://coq.inria.fr/bugs/show_bug.cgi?id=4549

**Comment by CohenCyril** [comment]
Since this issue is now in Coq, I close it. Feel free to reopen.
