### ISSUE TITLE
Naming policies should be documented

### ISSUE THREAD

**Issue by amahboubi** [math-comp/math-comp#182]
There used to be a description at the end of ssreflect's manual (see libs.tex in the sources). But I removed them and now this manual is a chapter in coq's own reference manual. I think even more accurate descriptions have been crafted for teaching purposes (COQWS17 at least?). We should have something in the wiki or in an .md file somewhere.

**Comment by CohenCyril** [comment]
Oh, actually, I forgot to follow up, but I did it in https://github.com/math-comp/math-comp/commit/e9754b2a3ca10377d52fb078452e1baf4b2013fc and https://github.com/math-comp/math-comp/commit/0a0aab74bc46581f7c126c93f51b9be71cc70ec8
