### ISSUE TITLE
Use Arguments to declare scopes

### ISSUE THREAD

**Issue by jashug** [math-comp/math-comp#184]
Continuing after #93 and #179, I'll work on changing the deprecated `Arguments Scope` to `Arguments`. Travis suggests about 300 occurrences. Helps work towards #90.

**Comment by jashug** [comment]
@maximedenes @gares `Arguments Scope` took only scope names
(so `Arguments Scope foo [type_scope]`), while `Arguments` takes either a scope name or bound key
(so either `Arguments foo _%type_scope` or `Arguments foo _%type`).

Which style should I adopt?

**Comment by gares** [comment]
The latter please (the short one).
