### ISSUE TITLE
ssreflect printing forgets "as" for list in pattern

### ISSUE THREAD

**Issue by thery** [math-comp/math-comp#188]
The ssreflect printing of list [:: _; _; _] seems to forget the "as" construct in pattern
Version

8.7.2
Operating system

linux
Description of the problem

Require Import List.

Definition foo (l : list nat) := 
  match l with
  | a :: ((b :: l) as l1) => l1
  | _ => l
end.

Print foo.

(*   ok

foo = 
fun l : list nat =>
match l with
| nil => l
| _ :: nil => l
| _ :: (_ :: _) as l1 => l1
end
*)

From mathcomp Require Import all_ssreflect.

Print foo.

(* not ok

foo = 
fun l : seq nat =>
match l with
| [::] => l
| [:: _] => l
| [:: _, _ & _] => l1
end
*)

**Comment by thery** [comment]
This is a copy of https://github.com/coq/coq/issues/7110

**Comment by gares** [comment]
I think you were badly advised. The bug may be worked around tuning a notation in seq, but the root bug must be in coq
