### ISSUE TITLE
[rewrite] does not work when primitive projections are involved

### ISSUE THREAD

**Issue by RalfJung** [math-comp/math-comp#19]
In the following code, the rewrite at the end of the file fails. If I remove "Set Primitive Projections", it success. Same if I use the Coq rewriter instead of the ssreflect one.

```
(* File reduced by coq-bug-finder  *)
Axiom proof_admitted : False.
Tactic Notation "admit" := case proof_admitted.
Require Import Coq.Setoids.Setoid.
Require Import Coq.Unicode.Utf8.

Require Import mathcomp.ssreflect.ssreflect.

Class Equiv A := equiv: relation A.
Infix "≡" := equiv (at level 70, no associativity).
Notation "(≡)" := equiv (only parsing).

Set Primitive Projections.

Class Dist A := dist : nat → relation A.
Notation "x ={ n }= y" := (dist n x y)
  (at level 70, n at next level, format "x  ={ n }=  y").


Record CofeMixin A `{Equiv A, Dist A} := {
  mixin_equiv_dist x y : x ≡ y ↔ ∀ n, x ={n}= y;
  mixin_dist_equivalence n : Equivalence (dist n);
  mixin_dist_S n x y : x ={S n}= y → x ={n}= y;
  mixin_dist_0 x y : x ={0}= y;
}.

Structure cofeT := CofeT {
  cofe_car :> Type;
  cofe_equiv : Equiv cofe_car;
  cofe_dist : Dist cofe_car;
  cofe_mixin : CofeMixin cofe_car
}.
Existing Instances cofe_equiv cofe_dist.
Arguments cofe_car : simpl never.

Section cofe_mixin.
  Context {A : cofeT}.
  Implicit Types x y : A.
  Lemma equiv_dist x y : x ≡ y ↔ ∀ n, x ={n}= y.
admit.
Defined.
End cofe_mixin.
  Context {A : cofeT}.
  Global Instance cofe_equivalence : Equivalence ((≡) : relation A).
  Proof.
    split.
    *
 intros x. rewrite equiv_dist.
```

This is with Coq 8.5 and Ssreflect 1.6.

This Coq bug may or may not be related - it occurs in the same code, but using an `apply` instead of a `rewrite`: <https://coq.inria.fr/bugs/show_bug.cgi?id=4529>

**Comment by gares** [comment]
Looks like a bug in ssreflect.  I can rewrite that lemma using `rewrite -> equiv_dist`.
The very weird thing is that `set G := ( _ ≡ _)` correctly grabs the goal, so it is not
ssreflect's specific pattern matching code that fails, even if the error message says
there is no instance of such pattern.  I'll look into that next week.  Thanks for reporting.

**Comment by gares** [comment]
I confirm ssr triggers Coq bug 4529, but the anomaly was hidden by mistake.
I'm closing this since the part of the bug in ssr is a catch-all not letting the Anomaly escape I've fixed.
I'm also looking at the bug in Coq, but no promises.
