### ISSUE TITLE
Windows installer for math-comp 1.7.0

### ISSUE THREAD

**Issue by ComFreek** [math-comp/math-comp#199]
(**TL;DR for math-comp book readers**: The latest working version pair of (Coq, math-comp) for me is ([8.7.0](https://github.com/coq/coq/tree/V8.6.1), [1.6.2](https://github.com/math-comp/math-comp/releases/tag/mathcomp-1.6.2)) both in 64 bit versions. But these versions apparently do not contain some notations yet which are used in the [math-comp book](https://math-comp.github.io/mcb/). I now resorted to firing up a Linux VM and installing the latest versions there.)

<hr>

I would appreciate having a Windows installer for the latest math-comp version 1.7.0 because the old 1.6.4 version (for which [an installer exists](https://github.com/math-comp/math-comp/releases)) is not compatible with Coq 8.8.0 and I have some problems manually installing math-comp.<br>
Neither could I get math-comp 1.6.4 working with Coq 8.7.1 or 8.7.2 as a temporary solution, see below.

<hr>

## Building math-comp 1.7.0 with Makefiles

Building it using the Makefile ([as documented here](https://github.com/math-comp/math-comp/blob/master/INSTALL.md)) neither works with Cygwin nor with Git Bash:

```
$ export PATH=$PATH:/c/coq/bin/
$ make
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
[…]
make: *** [all] Error 255
```

This is most probably due to `coqtop --config` outputting normal Windows paths instead of their equivalent Cygwin/Git Bash version (e.g. `/c/Coq/lib/` instead of `C:\Coq/lib/` for Git Bash and `/cygdrive/c/Coq/lib/` for Cygwin):

```
LOCAL=0
COQLIB=C:\Coq/lib/
DOCDIR=C:\Coq/doc/
OCAMLFIND=C:\coq64_inst\bin/ocamlfind.exe
CAMLP5O=C:\coq64_inst\bin/camlp5o.exe
CAMLP5BIN=C:\coq64_inst\bin/
[…]
```

I have not tried installing with OPAM yet, but the last time I installed the experimental version of OPAM for Windows, I could not even install Coq with it.

## Using math-comp 1.6.4 with Coq 8.7.1 or 8.7.2

The installation went fine in both cases, however, `From mathcomp Require Import all_ssreflect.` leads to the following error in Coq:

> Compiled library mathcomp.ssreflect.all_ssreflect (in file C:\Coq\lib\user-contrib\mathcomp\ssreflect\all_ssreflect.vo) makes inconsistent assumptions over library Coq.Init.Notations

This also happens with `all_algebra`:

> Compiled library mathcomp.algebra.all_algebra (in file C:\Coq\lib\user-contrib\mathcomp\algebra\all_algebra.vo) makes inconsistent assumptions over library Coq.Init.Notations

## Using math-comp 1.6.4 with Coq 8.6.1

``` Error:
File C:\Coq\lib\user-contrib\mathcomp\ssreflect\all_ssreflect.vo
has bad magic number 8700 (expected 8600). It
is corrupted or was compiled with another
version of Coq.
```

**Comment by gares** [comment]
Sorry for the late reply.

On windows + cygwin I typically `export PATH=/cygdrive/c/Coq:$PATH` and then `make && make install`.

I'll try to build an installer for you

**Comment by gares** [comment]
I confirm that, by setting `PATH` to `/cygdrive/c/Coq/bin/:$PATH` math-comp is building fine (Coq is installed using the official installers in `c:\Coq`)

**Comment by gares** [comment]
done
