### ISSUE TITLE
Wrong error message in rewrite with type class resolution

### ISSUE THREAD

**Issue by drouhling** [math-comp/math-comp#21]
The following code:

```
Class C (n : nat) := mkC {}.
(*Instance c : C 3 := mkC _.*)

Goal forall m : nat, (forall n, C n -> m = n) -> m = 3.
Proof.
  move=> m H.
  rewrite H.
```
leads to the following error message:

```
Error: The LHS of H
    m
does not match any subterm of the goal
```

The message is wrong since it matches m but cannot find an instance of class C or value for n.

**Comment by gares** [comment]
Yes, indeed TC resolution failure is considered as a failure by the pattern matching code.
I'll try to generate a less confusing error message.

**Comment by gares** [comment]
```
Error: The LHS of H
    m
matches but type classes inference fails
```

better ideas? @Barbichu ?  I can't be more specific since it may fail multiple times (i.e. it may match many different subterms and for each of them fail TC resolution in a different way)
