### ISSUE TITLE
doc of ssrbool, ssrfun and ssreflect are now hard to find

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#215]
they are not part of the online doc and also not available as the doc of Coq see coq/coq#8220

The bug is there since these files were merged into Coq

**Comment by CohenCyril** [comment]
@gares any updates on this?

**Comment by gares** [comment]
It is solved!

**Comment by gares** [comment]
It will be published along with the stdlib of Coq

**Comment by gares** [comment]
Here it is: https://coq.inria.fr/distrib/current/stdlib/
