### ISSUE TITLE
Please make your project compile with -w "+compatibility-notation"

### ISSUE THREAD

**Issue by Zimmi48** [math-comp/math-comp#222]
Please make your project compile with `-w "+compatibility-notation"` to prepare for the Coq 8.9 release. We would appreciate if this could be done ASAP. If you have trouble doing so, please raise your concern at coq/coq#8383.

**Comment by gares** [comment]
> We would appreciate if this could be done ASAP.

I've no idea of the amount of work this requires. Can you quantify it?

**Comment by Zimmi48** [comment]
Searching this warning in the GitLab CI logs tells me there are 9 lines to fix. BTW, given that math-comp (ssreflect or ssralg) is depended upon by many other packages, the sooner this is done, the sooner we can see if these other packages need fixing too or not. Thanks!

**Comment by gares** [comment]
I can to that...
