### ISSUE TITLE
bool_irrelevance should be named differently

### ISSUE THREAD

**Issue by anton-trunov** [math-comp/math-comp#229]
Let me cite a [comment](https://github.com/math-comp/finmap/issues/28#issuecomment-420630801) by @CohenCyril  which I agree with:

> the misnaming here would rather be `bool_irrelevance` since it is proof irrelevance for equalities of booleans... which by the way is subsumed by `eq_irrelevance` which deserves its name well...

Should `bool_irrelevance` be renamed or deleted altogether? Is there a policy on API-breaking changes?

**Comment by CohenCyril** [comment]
Indeed, a better name would be `bool_eq_irrelevance` or `eqb_irrelevance`... but indeed I am not sure it is needed at all...
We do not have yet a policy on API-breaking changes... we have to discuss it...

**Comment by CohenCyril** [comment]
> Yeah, I just replaced all (three) instances of`bool_irrelevance` with `eq_irrelevance` across FSCL and it worked flawlessly.

I did the same with math-comp https://github.com/CohenCyril/math-comp/tree/bool_irrelevance

**Comment by anton-trunov** [comment]
@CohenCyril Should this issue be closed?

**Comment by CohenCyril** [comment]
I forgot about it, but yes.
