### ISSUE TITLE
ltngtP

### ISSUE THREAD

**Issue by thery** [math-comp/math-comp#233]
commit d762ebb5a8c5191d49a75aa89ec34966de00eb9b

extends the use of ltngt

https://github.com/math-comp/math-comp/blob/5f8d45b54aa98732ec3de43d91814459d5a2f2e4/mathcomp/ssreflect/ssrnat.v#L450

from lt to leq so this lemma becomes somewhat wrongly named

**Comment by thery** [comment]
Here is what is puzzling me:

From mathcomp Require Import all_ssreflect.
Goal forall a b, a <= b <= a -> a = b.
by move=> a b; case: ltngtP.

**Comment by gares** [comment]
Looks like that the indexes of the spec are in the wrong order wrt what the name suggests.
Eg the one for == is matched before the one for < that is what one could expect.
@CohenCyril

**Comment by CohenCyril** [comment]
@thery, @gares: the commit you mention did not extend the lemma from `lt` to `leq`, there were and there are still three cases which are, in order of generated subgoals `m < n`, `m > n` and `m = n`, which reflects the choice of name. What changed are the matched indexes: I increased the number of indexes to match the ones of `ltrgtP` from  `ssrnum`, which causes more substitutions when performing  a `case`. I also preserved the order of the matching by keeping the equality in the last position (i.e. matched first) and putting the large inequalities in the first position (i.e. matched last).

**Comment by thery** [comment]
Je suis sans ordinateur, donc je ne peux pas verifier mais le truc qui m'embetait je crois c' est que ca s' applique si il n' y avait pas de lt 
dans le but.

**Comment by thery** [comment]
oops it is not my day today, sorry for the previous comment in french. 

My point is that I find it weird a theorem called ltngtP applies when there is no > or < in the goal 

-- 
Laurent

**Comment by CohenCyril** [comment]
@thery that is true, it works even if there is no `_ < _` in the goal. Before the above mentioned commit, it used to work when there was a `_ == _` in the goal, and after it it also work when the goal contains `_ <= _`. So it does not apply only for `_ < _` but also for more situations, and indeed, a bit more than before.
What I mean, is that this theorem is not becoming misnamed by this commit. And it was not misnamed before, as it reflects the three case that are generated by a case analysis on this lemma.

**Comment by thery** [comment]
> What I mean, is that this theorem is not becoming misnamed by this 
> commit. And it was not misnamed before, as it reflects the three case 
> that are generated by a case analysis on this lemma.
>
> —
>


Not convinced but I can live with it ;-)

**Comment by gares** [comment]
My complaint was about the *order* of the indexes.
In particular the pattern for `==` is matched before the one for `<`.
So if I see `a < b && a == c` and I just write `case: ltngtP` it reasons on `a` and `c`.
I'm fine having an index for `==`, but I think it should come after the one for `<`.

**Comment by CohenCyril** [comment]
> I'm fine having an index for `==`, but I think it should come after the one for `<`.

Maybe, but that would be a breaking change, whereas the 5f8d45b54aa98732ec3de43d91814459d5a2f2e4 tries to be conservative.

**Comment by gares** [comment]
Right, the order was already "wrong", at least to me. My remark is not related to the change, so we stay as we are I'd say.
