### ISSUE TITLE
Coq bench failing

### ISSUE THREAD

**Issue by SkySkimmer** [math-comp/math-comp#238]
Since sometime between https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/563/console (29-Oct-2018 00:19) and https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/564/console (29-Oct-2018 13:14) mathcomp has been failing on the Coq bench system.
~~~
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[coq-mathcomp-fingroup: make 1] Command started
+ make "-C" "mathcomp/fingroup" "-j" "1" (CWD=/home/jenkins/workspace/benchmark-part-of-the-branch/564/opam.NEW/4.05.0/build/coq-mathcomp-fingroup.dev)
- make: Entering directory '/home/jenkins/workspace/benchmark-part-of-the-branch/564/opam.NEW/4.05.0/build/coq-mathcomp-fingroup.dev/mathcomp/fingroup'
- make: Leaving directory '/home/jenkins/workspace/benchmark-part-of-the-branch/564/opam.NEW/4.05.0/build/coq-mathcomp-fingroup.dev/mathcomp/fingroup'
- make: *** No rule to make target '"Make"', needed by 'Makefile.coq'.  Stop.
[coq-mathcomp-fingroup: sh] Command started
+ sh "-c" "rm -rf '/home/jenkins/workspace/benchmark-part-of-the-branch/564/opam.NEW/4.05.0/lib/coq/user-contrib/mathcomp/fingroup'" (CWD=/home/jenkins/workspace/benchmark-part-of-the-branch/564/opam.NEW/4.05.0/build/coq-mathcomp-fingroup.dev)
~~~
Possible culprits are on the Coq side coq/coq#8812 and coq/coq#8763 (I don't see how those could lead to the error above) and (unless I messed up my dates) on the mathcomp side #219.

**Comment by CohenCyril** [comment]
@SkySkimmer thanks for the information, could you tell me how to reproduce this error on my side?

**Comment by CohenCyril** [comment]
@SkySkimmer please reopen if it does not fix the issue.

**Comment by SkySkimmer** [comment]
It's fixed, see 
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/567/console

Gaëtan Gilbert
