### ISSUE TITLE
Wishlist: provide Docker images for stable and dev versions of Math-Comp

### ISSUE THREAD

**Issue by erikmd** [math-comp/math-comp#243]
Dear MathComp developers,
This issue is basically a follow-up of the discussion started in https://github.com/CoqEAL/CoqEAL/pull/12 regarding the use of Docker images in the CI of MathComp-based projects: In particular, @CohenCyril suggested to provide not only an image for stable versions of Coq and MathComp, but also an image for the latest development version of MathComp.
I also Cc @strub who relies too on Docker-based CI in https://github.com/math-comp/multinomials 

As announced recently in coq-club, Docker images for Coq (defined in [this coq-community repo](https://github.com/coq-community/docker-coq/wiki)) are available on [Docker Hub](https://hub.docker.com/u/coqorg/) for stable/beta releases of Coq and Coq `dev` (nightly build).
So it would be great if you could distribute related images for MathComp as well! (e.g., by installing the `coq-mathcomp-character` opam package).

Hence this issue to summarize several details on this topic:
- first, you may want to create an organization on Docker Hub such as `mathcomp` (the hyphens are not allowed in the Docker Hub namespace identifiers, and https://hub.docker.com/u/mathcomp/ seems still available :-)
- another useful ingredient will be a GitHub repo named e.g. `docker-mathcomp`, to store stable Dockerfiles that would be used by a Docker Hub automated repo; for the corresponding Dockerfiles, you could take a look at [that of the coq-community/docker-coq repo](https://github.com/coq-community/docker-coq/blob/master/Dockerfile)
- regarding the `mathcomp-dev` build, there are several solutions possible but to avoid building the image twice (in the CI and in a Docker Hub automated build), you may want to build the image once for each mathcomp CI build and push afterwards in case of success (to a non-automated Docker Hub repo), using a Travis CI config similar to [that demo for example](https://github.com/erikmd/docker-coq-travis-ci-demo-2), see also the wrap-up I had written in this wiki [https://github.com/erikmd/coq-images/wiki/Testing-Docker-Hub-for-Coq](https://github.com/erikmd/coq-images/wiki/Testing-Docker-Hub-for-Coq#how-to-trigger-the-build-for-a-mathcomp-dev-image---untested)
- regarding the stable `mathcomp` builds, I've written a small python tool to help maintaining the `docker-coq` Git repo that you might find useful: https://github.com/erikmd/docker-hub-helper

Finally there are two questions that are not obvious from a maintenance perspective:
1. what should be the naming convention of the images, and the selected versions to distribute?
2. what should be the release policy when, e.g., a new stable version of MathComp is released?

About point 1., as `coq-mathcomp-character.1.7.0` is compatible with three versions of Coq and as the `+` is not allowed in the naming of Docker image tags but `-` and `_` are, possible namings could be:

- `mathcomp/mathcomp:1.7.0_coq-8.6`
- `mathcomp/mathcomp:1.7.0_coq-8.7`
- `mathcomp/mathcomp:1.7.0_coq-8.8` = `mathcomp/mathcomp:1.7.0`
- `mathcomp/mathcomp:1.7.0_coq-dev`

or

- `mathcomp/mathcomp:1.7.0-coq-8.6`
- `mathcomp/mathcomp:1.7.0-coq-8.7`
- `mathcomp/mathcomp:1.7.0-coq-8.8` = `mathcomp/mathcomp:1.7.0`
- `mathcomp/mathcomp:1.7.0-coq-dev`

(The `mathcomp:1.7.0-coq-dev` could be automatically rebuilt after the nightly build of `coqorg/coq:dev` by using the "repository links" feature of Docker Hub.)

About point 2., I guess this is mostly a maintenance choice w.r.t. the scalability of the builds… (e.g. you could decide whether you'd like to distribute only one stable version of `mathcomp` × 3 version of Coq, or 2 stable versions, or more…)
FYI for the `docker-coq` images, we decided to only build the last patchlevel version of each stable/beta release, so this amounts to 7 stable images overall currently:
- `coqorg/coq:8.4.6` = `coqorg/coq:8.4`
- `coqorg/coq:8.5.3` = `coqorg/coq:8.5`
- `coqorg/coq:8.6.1` = `coqorg/coq:8.6`
- `coqorg/coq:8.7.2` = `coqorg/coq:8.7`
- `coqorg/coq:8.8.2` = `coqorg/coq:8.8`
- `coqorg/coq:8.9-beta1` = `coqorg/coq:8.9`

Thoughts on these questions?

**Comment by CohenCyril** [comment]
- https://hub.docker.com/u/mathcomp is created, I gave @erikmd access rights (please give me your docker ids if you want me to add you)
- https://github.com/math-comp/docker-mathcomp is created as well

**Comment by anton-trunov** [comment]
> please give me your docker ids if you want me to add you)

@CohenCyril I'm `antontrunov` at Docker Hub. Thanks!

**Comment by erikmd** [comment]
Thanks @CohenCyril! as I'm not member of the math-comp github org, could you grant me access to the 
https://github.com/math-comp/docker-mathcomp repo as well?
@anton-trunov as the handling of mathcomp stable images (using e.g. the small tool [docker-hub-helper](https://github.com/erikmd/docker-hub-helper) I had prepared to this aim) and mathcomp dev images are a bit orthogonal, if you want I could help setting up the stable images, while you'd experiment further #256 regarding the setup of dev images with GitLab CI?

**Comment by erikmd** [comment]
@CohenCyril I've just configured the docker hub repo and started the automated builds.

If everything is fine, 4 images for MathComp 1.7.0 will be available tomorrow (in ~4h a priori).

To give more details, I have created 2 Docker Hub repos:
* https://hub.docker.com/r/mathcomp/mathcomp-dev (for which `docker push` is allowed, so this repo could be used to gather the mathcomp:dev images mentioned in #256, Cc @anton-trunov)
*  https://hub.docker.com/r/mathcomp/mathcomp (for which a direct `docker push` is disallowed and replaced with the automated build feature, connected with the [docker-mathcomp](https://github.com/math-comp/docker-mathcomp) Git repo)

Regarding the naming convention I was asking in my first post, I subjectively opted for:
* `mathcomp/mathcomp:1.7.0-coq-8.6`
* `mathcomp/mathcomp:1.7.0-coq-8.7`
* `mathcomp/mathcomp:1.7.0-coq-8.8`
* `mathcomp/mathcomp:1.7.0-coq-dev`

but feel free to say whether you disagree with that choice, if you prefer using an underscore separator e.g. `mathcomp/mathcomp:1.7.0_coq-dev`.

**Comment by erikmd** [comment]
Hi all, here is a summary of the current state of #243, #256 and #245 using Docker and GitLab CI:

## Stable versions of MathComp

As said in my previous comment, four [Docker images](https://hub.docker.com/r/mathcomp/mathcomp/tags) are now available for mathcomp 1.7.0:
* they straightforwardly reuse the `coqorg/coq` images (which provide Coq 8.6 in one OPAM switch `4.02.3`, and Coq 8.7+ in two OPAM switches `4.05.0` and `4.07.0+flambda`, see also [this page](https://github.com/coq-community/docker-coq/wiki#supported-tags))

* one can now run a Coq dev toplevel with mathcomp 1.7.0 and OCaml 4.05.0 by doing  
    `docker run --rm -it mathcomp/mathcomp:1.7.0-coq-dev rlwrap coqtop`

* I have set up another CRON task similar to that of `coqorg/coq:dev` so that `mathcomp/mathcomp:1.7.0-coq-dev` is rebuilt subsequently every night.  
      
    (before that I had tried Docker Hub's repository link feature to automatically rebuild a child image, say `mathcomp/mathcomp:*-coq-dev`, once `coqorg/coq:dev` is rebuilt, but (1) it wasn't precise enough as it triggered the rebuild of all `mathcomp/mathcomp:*` images, and moreover (2) that repository link feature is not available anymore in the [new Docker Hub service](https://blog.docker.com/2018/12/the-new-docker-hub/) deployed since 2018-12-13.)

Regarding the CI build time saving, to give a few figures measured on my laptop:
* docker-compiling mathcomp 1.7.0 on two switches with Coq dev prebuilt would take 22'54
* docker-compiling mathcomp 1.7.0 on two switches with Coq dev rebuilt from scratch would take 41'07

## CI and dev version of MathComp

I now have a working `.gitlab-ci.yml` configuration in [this GitLab repo](https://gitlab.com/erikmd/docker-hub-gitlab-ci-demo/) that test-builds GitHub branches. It has the following features:

* In a **build** stage, it builds mathcomp-dev for Coq-{8.6, 8.7, 8.8, dev} in 4 different jobs
    * the OPAM_SWITCH can be chosen if need be, since for Coq ≥ 8.7 two switches are available
        (including 4.07.0+flambda which should lead to faster compilation)
    * if the branch is `master` (protected branch), 4 Docker images `mathcomp-dev:master-coq-8.6` etc. are pushed to Docker Hub [(cf. test)](https://hub.docker.com/r/erikmd/mathcomp-dev-demo/tags);
    * otherwise (for all other branches) the 4 Docker images `mathcomp-dev:branch-name-coq-8.6` etc. are pushed to GitLab's Docker registry [(cf. test)](https://gitlab.com/erikmd/docker-hub-gitlab-ci-demo/container_registry).

* In a **test** stage, it runs the appropriate Docker image (according to a COQ_VERSION variable and according to the branch at stake) in as many jobs as desired, namely:
    * 1 job per selected mathcomp-based project and per Coq version;
    * possibility to select the CONTRIB_VERSION (`master` or so) that will be compatible with the specified COQ_VERSION (this follows an [earlier suggestion](https://github.com/math-comp/math-comp/pull/256#issuecomment-444319550) by @ejgallego)

In order to have a standalone `.yml` file as concise and extensible as possible, I used hidden jobs inheritance with several nested `extends:` rather than map-merging with `<<:`, and the `script` to compile a given contrib thus can be factored-out even if it is tested with several Coq versions.

### What remains to be done

* [ ] Create the math-comp GItLab CI mirror repo: https://gitlab.com/import/github/status?ci_cd_only=true (I cannot do this myself because I'm only collaborator on the [docker-mathcomp](https://github.com/math-comp/docker-mathcomp) repo, not the main repo [math-comp](https://github.com/math-comp/docker-mathcomp) itself); could a mathcomp owner help for this step?
* [ ] Adapt my current configuration (especially regarding the `Dockerfile`s) and open a new PR similar to #256, but for GitLab CI (I can do it soon)
* [ ] Support the CI build of GitHub PRs.  
    If I'm not mistaken the overall algorithm used in Coq's CI consists in pushing special branches in GitLab from PR fork branches? @Zimmi48 @ejgallego is it easy to setup this? would it also work for PR upstream branches (not forks)? (I guess this question is also related to the last remaining checkbox mentioned by @Zimmi48 in https://github.com/coq/coq/issues/7753#issue-330864529 :)
* [ ] Add selected mathcomp-based projects to the CI.
