### ISSUE TITLE
idfun vs id in cloning constructors

### ISSUE THREAD

**Issue by anton-trunov** [math-comp/math-comp#247]
A quick search through the math-comp library shows some cloning constructors
use `idfun` and `id` in the same expression, e.g.

```
ssreflect/eqtype.v:134:Notation "[ 'eqType' 'of' T 'for' C ]" := (@clone T C _ idfun id)
ssreflect/eqtype.v:600:Notation "[ 'subType' 'of' U 'for' v ]" := (clone_subType U v id idfun)
algebra/ssralg.v:1779:Notation "[ 'additive' 'of' f 'as' g ]" := (@clone _ _ _ f g _ _ idfun id)
algebra/ssralg.v:1986:Notation "[ 'rmorphism' 'of' f 'as' g ]" := (@clone _ _ _ f g _ _ idfun id)
algebra/ssralg.v:2201:Notation "[ 'linear' 'of' f 'as' g ]" := (@clone _ _ _ _ _ f g _ _ idfun id)
```
At a *quick glance* it seems there is no difference between using `id` and `idfun` for *this* purpose:
```coq
From mathcomp Require Import all_ssreflect.

Check id.
(*
id : ?T -> ?T
where ?T : [ |- Type]
*)

Check idfun.
(*
idfun : ?T -> ?T
where ?T : [ |- Type]
*)
```

So, we can make two types unify using both `id` and `idfun`, and those get stripped off with `Eval hnf in `.
Also, the project compiles if I replace all `idfun`s in *cloning constructors* with `id`s
and there is no performance penalty on my hardware.

Could we have the original train of thought documented somewhere? Thank you.

**Comment by ggonthier** [comment]
As idfun and id are convertible values this should be expected. However using different values makes it possible to pretty print various flavors of cloning as they are input (e.g., deciding whether to print a ‘for’).
    Cheers,
Georges 

Envoyé de mon iPhone

**Comment by anton-trunov** [comment]
> However using different values makes it possible to pretty print various flavors of cloning as they are input (e.g., deciding whether to print a ‘for’).

Ah, yes, this makes perfect sense. Thank you!

Where would one put a comment like this? I think it would be useful for the future library users.

**Comment by ggonthier** [comment]
It's a bit of a dilemma: on the one hand commenting every instance of this code pattern would clutter the library, on the other hand a single comment in `eqtype` where it first occurs is likely to be missed by a casual peruser of the library...

**Comment by anton-trunov** [comment]
May I suggest to put it into `ssrfun`, where `id` and `idfun` are defined?
When I saw this pattern I went to read `ssrfun`'s header and then the part where those notations are defined.

**Comment by ggonthier** [comment]
The natural place to do so would be the documentation of `phantom_id` - where the explanation for the `id` arguments is given. But had you looked up that (rather technical) paragraph?

**Comment by anton-trunov** [comment]
>The natural place to do so would be the documentation of phantom_id

I agree, this is a better place.

> But had you looked up that (rather technical) paragraph?

Yes, I read it, but from that paragraph
```
(* we can avoid specifying st directly by calling foo (@id t), or specify     *)
(* the call completely while still ensuring the consistency of t and st, by   *)
(* calling @foo t st idfun.  *)
```
it wasn't clear why use `idfun` in the second example.

**Comment by anton-trunov** [comment]
@ggonthier Thank you!
