### ISSUE TITLE
no longer compiles with coq trunk

### ISSUE THREAD

**Issue by spacekitteh** [math-comp/math-comp#26]
Since this change: https://github.com/coq/coq/commit/15b28f0ae1e31506f3fb153fc6e50bc861717eb9

affected red_in_concl.

**Comment by gares** [comment]
We know.  Unfortunately you cannot rely on ssreflect compiling every day on trunk.  Pull requests fixing compilation, typically submitted by the author of the API change, are quickly accepted.  But if there is no such pull request we don't have energy to fix compilation ourselves promptly.  It will eventually fixed, but I advise you against a workflow that involves tracking coq trunk daily and requiring ssreflect to build.  It is unfortunate, I know.
