### ISSUE TITLE
Availability of archive of MathComp versions before 1.6

### ISSUE THREAD

**Issue by palmskog** [math-comp/math-comp#267]
The MathComp [website](https://math-comp.github.io/math-comp/) currently links to a [historic archive](http://ssr.msr-inria.inria.fr/FTP/) for versions older than 1.6. However, this link currently leads to a "404 not found" page.

It appears as though archive.org has [preserved](https://web.archive.org/web/20170102190522/http://ssr.msr-inria.inria.fr/FTP/) the version archive, but I think these versions should be made available more conveniently for researchers.

**Comment by gares** [comment]
You are right, we disabled the old website just before the Christmas break.
I'll try to upload all the tarballs we released on github next week.

**Comment by gares** [comment]
I've made a tag called archive, and uploaded to that github release all the tarballs I've got and listed their dates.

**Comment by gares** [comment]
https://github.com/math-comp/math-comp/releases/tag/archive

**Comment by gares** [comment]
Oh, if you are digging out the history of the project, you may be interested in some data we used in this talk http://videos.rennes.inria.fr/Conference-ITP/indexAssiaMahboubiEnricoTassi.html see the slides at http://videos.rennes.inria.fr/Conference-ITP/slidesMathematicalComponents.pdf (slides 11, 12 and 41).
