### ISSUE TITLE
ci: overloaded-lemma broken

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#276]
see coq-community/lemma-overloading#34

they compile turning earnings into errors and on master `=> {X} X` warns you that you have a duplicate clear. We have a bunch of these in MC too, but we shall wait until 8.11 is released before using that proof language feature.

**Comment by CohenCyril** [comment]
@ejgallego @erikmd isn't it problem that some packages are in the pipeline of mathcomp but not that of Coq... so that when ssreflect gets breaking changes they are not tested by coq on all developments that mathcomp tests?

**Comment by ejgallego** [comment]
Indeed that could be the case @CohenCyril , please file a bug report in Coq so we eventually add them.

**Comment by gares** [comment]
fixed, I don't get why github is not closing this automatically
