### ISSUE TITLE
clean up using printing only notations

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#310]
Grep for:
- strings interrupted by `'  '`
- strings starting with `\` a string and  then a blank and the continuation of string

Examples:
- in `mathcomp/ssreflect/finset.v`
  + `Notation "[ 'se' 't' E | x 'in' A , y 'in' B ]"`
  + `Notation "[ 'se' 't' E | x 'in' A , y 'in' B & P ]"`
  + `Notation "[ 'se' 't' E | x : T , y : U 'in' B ]"`
  + `Notation "[ 'se' 't' E | x : T , y : U 'in' B & P ]"`
  + `Notation "[ 'se' 't' E | x : T 'in' A , y : U ]"`
  + `Notation "[ 'se' 't' E | x : T 'in' A , y : U & P ]"`
  + `Notation "[ 'se' 't' E | x : T , y : U ]"`
  + `Notation "[ 'se' 't' E | x : T , y : U & P ]"`]
- in  `mathcomp/ssreflect/fintype.v`
  + `Notation "[ 'pic' 'k' x : T ]" := [pick x : T | pick_true _]`
- in `mathcomp/ssreflect/eqtype.v`
  + `Notation "[ 'sub' 'Type' 'for' v ]" := (SubType _ v _ _ vrefl_rect)`
  + `Notation "[ 'new' 'Type' 'for' v ]" := (NewType v _ _ vrefl_rect)`

**Comment by ggonthier** [comment]
All such notation will be ‘only parsing’ as well, so perhaps that would be an easier filter.

Envoyé de mon iPhone

**Comment by CohenCyril** [comment]
@LaurenceRideau @ybertot @thery this is an unglamorous piece of work... Would one of you be up for it?
