### ISSUE TITLE
Drop support for 8.6

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#313]
and remove the `plugins/` folder. After 8.6 ssreflect is part of Coq. MC 1.8.0 can support 8.7, 8.8, 8.9 and very probably 8.10, so I don't think we should care about 8.6 anymore.

**Comment by CohenCyril** [comment]
I agree with you!

**Comment by CohenCyril** [comment]
@gares, this is to my knowledge the last item of the 1.8.0 milestone. Can you take care of it?
