### ISSUE TITLE
Purpose of "EqTypePred"

### ISSUE THREAD

**Issue by francoisthire** [math-comp/math-comp#329]
I don't understand the meaning of this module defined here: 
https://github.com/math-comp/math-comp/blob/98c66b28153d7c7d520a96fb73570e80651bd47d/mathcomp/ssreflect/eqtype.v#L294

If I do:
```
grep -i "eqtypepred"
```
I get
```
mathcomp/ssreflect/eqtype.v:288:Module Type EqTypePredSig.
mathcomp/ssreflect/eqtype.v:290:End EqTypePredSig.
mathcomp/ssreflect/eqtype.v:291:Module MakeEqTypePred (eqmod : EqTypePredSig).
mathcomp/ssreflect/eqtype.v:293:End MakeEqTypePred.
mathcomp/ssreflect/eqtype.v:294:Module Export EqTypePred := MakeEqTypePred Equality.
```

Is it safe to remove this module then?

**Comment by CohenCyril** [comment]
> Is it safe to remove this module then?

No... If you read the comment above that portion of code, you will notice this is all about the coercion `Coercion eqmod.sort : eqType >-> predArgType.` which is exported by this module. If you remove the module, the coercion is not exported and compilation fails later.

**Comment by CohenCyril** [comment]
@francoisthire I will close this issue. Feel free to reopen it if you have more related questions.
