### ISSUE TITLE
website coqdoc outdated / release process incomplete

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#361]
At some point @maximedenes made the website available at https://math-comp.github.io/ but the release process documented at https://github.com/math-comp/math-comp/wiki/Howto-Release misses a step to synchronize the websites (since the authoritative contents are still in the .../math-comp/ repo I guess).

**Comment by gares** [comment]
CC @CohenCyril @affeldt-aist Ping @maximedenes

**Comment by gares** [comment]
FTR, the website at http://math-comp.github.io/math-comp/ has the update coqdoc, while the one at https://math-comp.github.io/ has not!

**Comment by affeldt-aist** [comment]
I didn't realize the website was duplicated.

**Comment by gares** [comment]
it's a bug ;-)

**Comment by CohenCyril** [comment]
Should we take down http://math-comp.github.io/math-comp/ or keep it as a documentation-specific website?

**Comment by CohenCyril** [comment]
PS: Many websites might still reference http://math-comp.github.io/math-comp/ as the main page, so I advocate we keep the page alive but re-purpose it as I said. What do you think?

**Comment by amahboubi** [comment]
I think that keeping the two  is a bad idea, because it will be too confusing for both users and maintainers of the website. 

Can't we just redirect http://math-comp.github.io/math-comp/ to http://math-comp.github.io?

**Comment by CohenCyril** [comment]
> Can't we just redirect http://math-comp.github.io/math-comp/ to http://math-comp.github.io?

I don't know how to do that...

**Comment by CohenCyril** [comment]
> Can't we just redirect http://math-comp.github.io/math-comp/ to http://math-comp.github.io?

yes I think we can

**Comment by amahboubi** [comment]
But this redirection topic is slightly different from the one of the present issue, which is about the bad version of the documentation linked from  http://math-comp.github.io.

**Comment by amahboubi** [comment]
Ping @maximedenes .

**Comment by maximedenes** [comment]
Sorry for this confusing situation. Can you clarify what you want me to do?

**Comment by amahboubi** [comment]
Today the coqdoc documentation linked from the new location of the website is outdated. E.g.:
https://math-comp.github.io/htmldoc/mathcomp.ssreflect.ssreflect.html
The one is sync lives at the previous location. E.g.:
http://math-comp.github.io/math-comp/htmldoc/mathcomp.ssreflect.ssreflect.html

Actions  needed:
1. repair
2. update the release instructions so that this does not happen anymore
3. Redirect http://math-comp.github.io/math-comp/ to http://math-comp.github.io

Point 3 is addressed by #365 but points 1 and 2 are not done, and should precede 3.

**Comment by maximedenes** [comment]
Working on 1.

For 2., I'll need to discuss with @gares how to separate concerns between math-comp proper and the website. The current html doc build script does very strange things, including mangling source files in place without warning... Not sure I can write reliable and reasonable release instructions with this state of affairs.

**Comment by amahboubi** [comment]
> Working on 1.
Many thanks @maximedenes !

**Comment by maximedenes** [comment]
Wait! @gares didn't your `import-doc` Makefile target already address this?

https://github.com/math-comp/math-comp.github.io/blob/master/Makefile

The file header is a bit terse.

**Comment by maximedenes** [comment]
> including mangling source files in place without warning

And of course it is not idempotent. So I got incorrect results, and will need to rebuild math comp entirely. Please bear with me.

**Comment by gares** [comment]
> https://github.com/math-comp/math-comp.github.io/blob/master/Makefile

This should be dropped (it was used when we could not release by tagging master).

>  including mangling source files in place without warning... Not sure I can write reliable and reasonable release instructions with this state of affairs.

The Makefile in https://github.com/math-comp/math-comp/blob/master/docs/htmldoc/Makefile is idempotent when it succeeds (it checks your tree is clean and  uses git to restore the old files at the end).

If you move the Makefile elsewhere you could get in input the git url to clone (a tag for the release, a branch for testing things)

**Comment by maximedenes** [comment]
> The Makefile in https://github.com/math-comp/math-comp/blob/master/docs/htmldoc/Makefile is idempotent when it succeeds (it checks your tree is clean and uses git to restore the old files at the end).

Yeah but a successful build is typically one you don't restart, whereas failing ones...

**Comment by maximedenes** [comment]
> If you move the Makefile elsewhere you could get in input the git url to clone (a tag for the release, a branch for testing things)

Yes, I think that's what we should do (although not sure it should be a `Makefile`). This way we could solve both problems, by working on a temporary copy of the repo (no modification in place) and not relying on the doc and the sources being in the same repo.

**Comment by gares** [comment]
It leaves you the thing that did not compile, so that you can inspect it. I really don't get what the problem is.

**Comment by maximedenes** [comment]
> It leaves you the thing that did not compile, so that you can inspect it. I really don't get what the problem is.

The problem (IIUC) is that when you fix the problem and relaunch the build, it will mangle the sources more, and you get formatting issues in the final html.

**Comment by gares** [comment]
Then the check must be incomplete (since I guess you did not commit the mangled sources).
The script should just refuse to run if the sources are already mangled (it could be smarter, but this is not the problem here). Why does not it stop saying you have uncommitted changes?

**Comment by maximedenes** [comment]
Yes, the test is broken. We are discussing it in the other thread.

Anyway, it seems I finally got the updated HTML documentation. Will create a PR.

**Comment by maximedenes** [comment]
@amahboubi For 1., see https://github.com/math-comp/math-comp.github.io/pull/7

**Comment by amahboubi** [comment]
Very good, thanks! One last thing regarding 1 and 3. As far as I can see, we now how two versions of the coqdoc,e.g.:
https://math-comp.github.io/htmldoc/mathcomp.ssreflect.ssreflect.html
and
http://math-comp.github.io/math-comp/htmldoc/mathcomp.ssreflect.ssreflect.html

Today, there are identical, but will they stay so? Can we either remove the 2nd one, or redirect to the first? It seems  to me that #365 only addresses the re-direction of the root of the site. @CohenCyril can you confirm?
