### ISSUE TITLE
Add "coq", "ssreflect" tags to the description of Mathcomp repository

### ISSUE THREAD

**Issue by anton-trunov** [math-comp/math-comp#366]
and maybe add even more tags.

This should make Mathcomp more visible when people filter projects on GitHub by tags. E.g. math-comp does not show up here: https://github.com/topics/ssreflect

**Comment by anton-trunov** [comment]
It would be nice to have https://math-comp.github.io in the "website" section of the description (it shows up when one clicks the "edit" button).

**Comment by CohenCyril** [comment]
> and maybe add even more tags.

I added some tags

**Comment by anton-trunov** [comment]
Awesome! Thank you
