### ISSUE TITLE
leq_subr misnamed?

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#398]
https://github.com/math-comp/math-comp/blob/cd81418979c9783f9dae65d2aea98742919420e5/mathcomp/ssreflect/ssrnat.v#L520

It looks to me that this lemma should be called `leq_subl` (because the subtraction is on the left). Am I right or am I missing something?

**Comment by anton-trunov** [comment]
I thought the name has the `r` suffix because we subtract from `n`, focusing on the subtrahend `m`, which is on the right relatively to `-` operator. Essentially what I'm saying is that it seems the `l` / `r` suffixes bind more strongly to the operator they get appended to, not the head symbol.

**Comment by CohenCyril** [comment]
well it depdends, I could see you are right in some cases, but in others, where there is no repetition of variable in the LHS (like in `mulnDl`) the `l` (or `r`) suffix binds to the the head symbol.
