### ISSUE TITLE
Having `minn` and `maxn` in the arguments of `leqP`, `ltnP`, and `ltngtP`

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#404]
> BTW, having `minn` and `maxn` in the arguments of `leqP`, `ltnP`, and `ltngtP` could be nice. But we need to reorder definitions and lemmas in ssrnat. (In this case, how should we order their arguments?)

_Originally posted by @pi8027 in https://github.com/math-comp/math-comp/pull/378#issuecomment-527908554_

**Comment by anton-trunov** [comment]
Sometimes I wish those rules had also `subn`, but I fear it would be too much.

**Comment by pi8027** [comment]
@CohenCyril @anton-trunov I will try both ideas and see how it work.

**Comment by pi8027** [comment]
@CohenCyril Could you update the title of this issue?: Having `subn` in the arguments of `leqP`, `ltnP`, and `ltngtP`

**Comment by CohenCyril** [comment]
@pi8027 
> @CohenCyril Could you update the title of this issue?: Having `subn` in the arguments of `leqP`, `ltnP`, and `ltngtP`

Maybe we should rather close this issue and open a new one...

**Comment by pi8027** [comment]
@CohenCyril Done. Please close this one.
