### ISSUE TITLE
Check that every new symbol or canonical of ssralg for the next release is duly exported.

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#425]
Since we regularly forget to put things to `GRing.Theory`, it's probably good to check the whole diff of ssralg after the latest release to find this kind of mistake before the next release.

_Originally posted by @pi8027 in https://github.com/math-comp/math-comp/pull/421#issuecomment-553963191_

**Comment by ybertot** [comment]
The check was done as follows:
- all new lemmas are commrB, commr_sum, commr_prod, comm_alg
- New export modules are ComAlgebra.Exports, ComUnitAlgebra.Exports
- New independent Canonical structures are regular_comAlgType, regular_comUnitAlgType
The presence of all new lemmas has been verified in GRing.Theory.
The presence of Exports modules has been verified.
The presence of independent Canonical structures has been verified.

There remains a question of how to automate this verification.
