### ISSUE TITLE
Generalization of order (in fingraph.v) and related lemmas to non-frel graphs

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#442]
`order f x` (in fingraph.v) means the size of `f`-orbit of `x`:
```coq
Definition order (T : finType) (f : T -> T) (x : T) := #|fconnect f x|.
```
This definition can naturally be generalized to non `frel`-graphs, which means the number of reachable elements from `x` in general. Some lemmas that use `order` can probably be generalized as well. At least, the following lemma introduced by #261 seems to hold in general.
```coq
eq_order_cycle
     : forall p : seq T, fcycle f p -> {in p &, forall x y : T, order y = order x}
```

**Comment by pi8027** [comment]
I see that `order_gt0` and `orderSpred` can be generalized but I didn't find anything interesting to generalize in this way... If we somehow describe the (local) acyclicity of graphs, we may state that the order of `x` is equal to the sum of the orders of successors of `x` plus one if `x` is acyclic. But I still don't have good application of this generalization.

**Comment by chdoc** [comment]
> At least, the following lemma introduced by #261 seems to hold in general.
> 
> ```coq
> eq_order_cycle
>      : forall p : seq T, fcycle f p -> {in p &, forall x y : T, order y = order x}
> ```

I think you are mistaken. If `p` is a cycle for some non-functional relation, then every vertex on the cycle can have an arbitrary number of reachable vertices outside the cycle.

**Comment by pi8027** [comment]
@chdoc If `x` and `y` are on a cycle for some non-functional relation, `x` is reachable from `y`, thus any reachable element from `x` is also reachable from `y` (by transitivity), and vice versa. So `x` and `y` have the same number (and set) of reachable vertices. Did I make a mistake?

**Comment by chdoc** [comment]
No, indeed, I made the mistake. Not sure the generalized lemma is all that useful though.

**Comment by pi8027** [comment]
> Not sure the generalized lemma is all that useful though.

I agree with you on this point. I still don't see any useful application.

BTW, can `orbit` also be generalized using `dfs`, so that we can generalize more lemmas about `orbit` and `order` to non-functional relations? (But I guess there are only a few such the lemmas.)

**Comment by chdoc** [comment]
I'm not sure. I wouldn't call it "orbit", if it doesn't cycle. IIRC, most of the lemmas on `orbit` not only require the relation to be functional, but also require the function to be injective (i.e., a permutation). Otherwise the "orbit" becomes a "lasso". Orbits are used extensively in `fourcolor` for the three permutations making up a hypermap. I don't know how much this is used elsewhere.

**Comment by ybertot** [comment]
I use orbits in my development about triangulations, too, even though I am not using hypermaps: I find it is convenient to describe the convex hull of a set of points in the plane as the orbit of a function starting from one of the points on the hull, I also find it convenient to not impose that the function be injective.

**Comment by CohenCyril** [comment]
@chdoc @pi8027 unless someone finds an application to this generalization I suggest we close this issue.

**Comment by pi8027** [comment]
@CohenCyril I agree.
