### ISSUE TITLE
[make] doc target does not put libgraph.html in place

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#448]
The browseable library graph https://math-comp.github.io/htmldoc/libgraph.html is made of two files:
- `depend.js` generated by the `make doc` target via the Lua script
- `libgraph.html` static, just to be put in `htmldoc/`

Apparently with the last release the second file disappeared from both the website and the git repo of mathcomp. We should revive it and fix the Makefile to copy it into `htmldocs/`. Currently we get 404.

**Comment by gares** [comment]
CC @ybertot @maximedenes @chdoc

**Comment by ybertot** [comment]
I don't understand, I just added libgraph.html in the htmldoc directory, but the link given above is still invalid.

**Comment by ybertot** [comment]
The problem was not only the loss of file `libgraph.html` but also the whole directory `js` and eleven javascript files in it.

This is now repaired, and a coming PR for the make file is in the works.

**Comment by ybertot** [comment]
The preservation of libgraph.html and the js/ subdirectory is now documented in the `Howto Release` wiki page.
