### ISSUE TITLE
[Mac] Cannot find a physical path bound to logical path matching suffix <> and prefix mathcomp. 

### ISSUE THREAD

**Issue by triviality** [math-comp/math-comp#456]
I have macOS and I have installed coq, mathcomp via opam, while I have installed coqide via brew cask. I can't import ssreflect. It gives me the following error
 "Cannot find a physical path bound to logical path matching suffix"

Screenshots are attached.

<> and prefix mathcomp.
<img width="912" alt="Screen Shot 1441-05-28 at 4 11 07 PM" src="https://user-images.githubusercontent.com/16515822/72987208-f9c86680-3dfa-11ea-9121-ca5c003a6c3d.png">

<img width="674" alt="Screen Shot 1441-05-28 at 4 11 32 PM" src="https://user-images.githubusercontent.com/16515822/72987237-06e55580-3dfb-11ea-8115-9585069c1bdb.png">

**Comment by ejgallego** [comment]
I'm afraid this installation method is not supported; you must install the Coq stack with the same package manager; otherwise essential constraints such as the exact same OCaml compiler won't be satisfied.
