### ISSUE TITLE
Incompatibility with Ltac2

### ISSUE THREAD

**Issue by vlj** [math-comp/math-comp#467]
Hi,

the following sample doesn't work :

`
From Ltac2 Require Import Ltac2.
From Ltac2 Require Option.

Ltac2 hello_world () := Message.print (Message.of_string "Hello, world!").

From mathcomp Require Import ssreflect ssrnat eqtype ssrbool ssrnum ssralg.

Variable R: fieldType.

Variable saturation:R.

Open Scope ring_scope.

Import  GRing.Theory.

Definition NakaRushon x coeff :=
    x / (1%:R + x * (1 - coeff) / saturation).

Lemma tmp:
    forall x y:R, ~~(y == 0) -> x = x * y / y.
Proof.
    move => x y H.
`

It fails with the error message : `Syntax error: [tactic:q_ident] expected after 'move' (in [tactic:tac2expr]).`

Coq is at version 8.11, mathcomp at 1.10.

**Comment by vlj** [comment]
According to gitter chat @ppedrot and @gares may have info on this.

**Comment by gares** [comment]
Blind guess:
- move is (also) an ltac2 tactic
- ssr extends the tactic nonterminal of ltac1 only with the postfix `=> bla` thing

Can you write `idtac => x y` ?

**Comment by CohenCyril** [comment]
FTR, on gitter Pierre-Marie Pédrot @ppedrot Mar 26 18:34 said:
> this has been on my TODO list for quite a time actually
> (note that you can still implement stuff in Ltac2 and export it to Ltac1 so as to be able to use ssr)

**Comment by CohenCyril** [comment]
@ppedrot has this been opened on the Coq side?

**Comment by ppedrot** [comment]
I don't remember if there is an open bug, but it still on my TODO list...

**Comment by CohenCyril** [comment]
Would you mind opening an issue on the Coq side so that I can close it here and still get a reminder somewhere?

**Comment by ppedrot** [comment]
https://github.com/coq/coq/issues/12843
