### ISSUE TITLE
"contra" lemmas for propositions

### ISSUE THREAD

**Issue by chdoc** [math-comp/math-comp#491]
I've grown quite accustomed to using the various "contra" lemmas to be found `ssrbool`. However, sometimes the involved facts are actual propositions and their negations. For this purpose, I've started to use the following collection of lemmas:
```coq
Lemma contraTnot b (P : Prop) : (P -> ~~ b) -> (b -> ~ P).
Lemma contraNnot (b : bool) (P : Prop) : (P -> b) -> (~~ b -> ~ P).
Lemma contraPT (P : Prop) (b : bool) : (~~ b -> ~ P) -> P -> b.
Lemma contra_notT (b : bool) (P : Prop) : (~~ b -> P) -> ~ P -> b.
Lemma contraPN (b : bool) (P : Prop) : (b -> ~ P) -> (P -> ~~ b).
Lemma contraPneq (T:eqType) (a b : T) (P : Prop) : (a = b -> ~ P) -> (P -> a != b).
Lemma contraPeq (T:eqType) (a b : T) (P : Prop) : (a != b -> ~ P) -> (P -> a = b).
```
The naming scheme is inspired by the remaining contra lemmas, using "P" for assumptions with type in `Prop` and "not" for `~ P`. Do you think this is useful? Should I create a pull request?

**Comment by CohenCyril** [comment]
Hi, I'm all in favor, and for the sake of completeness, I would also add:
```coq
Lemma contraPnot (P Q : Prop) : (Q -> ~ P) -> (P -> ~ Q).
Lemma contra_not (P Q : Prop) : (Q -> P) -> (~ P -> ~ Q).
```
and I would add to math-comp/analysis/boolp.v the variants that are true classically.

**Comment by chdoc** [comment]
Okay, I will create a pull-request then. Any suggestions for finding places in the library where these should be used; that seems a rather daunting task.

**Comment by CohenCyril** [comment]
I think next to the other ones,
1. The ones without equality should go to ssrbool from mathcomp, next to the others with booleans, and merged simultaneously in Coq when it is ready for mathcomp.
2. The ones with equality should go in eqtype.
