### ISSUE TITLE
Bugfixes for 1.11.0

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#496]
- add again `maxr` lemmas (`maxrC`, ...)
- reincorportate `incnr_inj` etc,
- add missing `leW_mono` etc for order too.

**Comment by affeldt-aist** [comment]
@CohenCyril can we help doing the corresponding PR?

**Comment by ybertot** [comment]
This issue is blocking for the 1.11 release.

**Comment by CohenCyril** [comment]
I realized this issue was more complicated than I imagined.

> * add again `maxr` lemmas (`maxrC`, ...)

This is the description which was not accurate: I  opened a new issue specifically for this #515

> * reincorportate `incnr_inj` etc,
> * add missing `leW_mono` etc for order too. 

Fixed by  #513.
