### ISSUE TITLE
Missing allpairs lemma

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#497]
`allpair0s`, `allpairs0` and `cons` variants missing

**Comment by gares** [comment]
We should do it *now* .... or change the milestone

**Comment by pi8027** [comment]
We already have `allpairs_consr` as follows, and `allpair0s` and `allpairs_consl` can be done by conversion (but I don't oppose adding them). So I think the actual missing lemma is `allpairs0`. https://github.com/math-comp/math-comp/blob/6eceb3bc43342c0b4cb03716651a017ce88fed09/mathcomp/ssreflect/seq.v#L3176-L3181

**Comment by CohenCyril** [comment]
> We already have `allpairs_consr` as follows, and `allpair0s` and `allpairs_consl` can be done by conversion (but I don't oppose adding them). So I think the actual missing lemma is `allpairs0`.

Sure, I almost have a PR for that...

**Comment by CohenCyril** [comment]
Also, I noticed that `allpairs_consl` and `allpairs_catl` are not precise enough, so I added a version with `perm_eq`.

**Comment by ybertot** [comment]
allpairs_consl requires a little more than conversion, so it is definitely a worthwile addition.

<pre>
Lemma allpairs_consl f a s t :
  [seq f x y | x <- a :: s, y <- t x] =
  [seq f a y | y <- t a] ++ [seq f x y | x <- s, y <- t x].
Proof. by rewrite (allpairs_cat f [:: a] s t) /= cats0. Qed.
</pre>

**Comment by ybertot** [comment]
How about allpairs_rcons variants?

**Comment by CohenCyril** [comment]
No no, it is conversion, even though it is nice to have it for a finer grain control of rewrites and unfoldings.
```
Lemma allpairs_cons f x s t :
  [seq f x y | x <- x :: s, y <- t x] = 
    [seq f x y | y <- t x] ++ [seq f x y | x <- s, y <- t x].
Proof. by []. Qed.
```

**Comment by CohenCyril** [comment]
> How about allpairs_rcons variants?

There is `allpairs_consr` but I'm generalizing it.

**Comment by ybertot** [comment]
I meant `allpairs_rconsl` : interaction with the `rcons` function.

**Comment by CohenCyril** [comment]
> I meant `allpairs_rconsl` : interaction with the `rcons` function.

Nice catch! I'll add it to the batch as well.
