### ISSUE TITLE
[ssrnat] Suggestion of additional lemma: oddS

### ISSUE THREAD

**Issue by SnarkBoojum** [math-comp/math-comp#500]
Hi,

I was reading the book, and for one of the exercices (16 in 5.1.1), I missed a simple lemma on the odd predicate ; I propose to add it:

    Lemma oddS n: odd n.+1 = ~~ odd n.
    Proof.
      elim: n => [|n Hn] ; first by easy.
      by rewrite Hn.
    Qed.

which gave me:

    Lemma sum_odd n : \sum_ (0 <= i < n.*2 | odd i) i = n^2.
    Proof.
     elim: n => [|n Hn] ; first by rewrite unlock.
     rewrite doubleS.
     rewrite big_mkcond.
     rewrite big_nat_recr //.
     rewrite big_nat_recr //.
     rewrite odd_double oddS odd_double //=.
     rewrite -big_mkcond {}Hn.
     rewrite addn0 -!mulnn -addnn mulnS mulnC mulnS.
     ring.
    Qed.

I must admit I'm not satisfied by either proof, but as a beginner, getting a correct proof is already an achievement. [I find the last part about the (m.+1)^2=... especially awful].

**Comment by pi8027** [comment]
@SnarkBoojum `oddS` can be proved by `done`, `by []`, or `reflexivity` (actually its LHS and RHS are convertible) and `sum_odd` can be proved in 3 lines without use of `oddS`:
```coq
Lemma sum_odd n : \sum_ (0 <= i < n.*2 | odd i) i = n^2.
Proof.
rewrite big_mkcond; elim: n => [|n Hn]; first by rewrite big_nil.
rewrite doubleS 2?big_nat_recr //= odd_double /= Hn (sqrnD 1) mul1n mul2n.
by nat_norm.
Qed.
```

**Comment by CohenCyril** [comment]
I guess it would be harmless to provide:
```coq
Lemma oddS n: odd n.+1 = ~~ odd n. Proof. by []. Qed.
```
in the library.

**Comment by SnarkBoojum** [comment]
Well, from reading the book, I learnt how to look for existing lemmas, found about odd_double, but nothing to simplify what I had, so I wrote oddS.

I hadn't found sqrnD, and I'll have to check what nat_norm does.
