### ISSUE TITLE
Suggestions for various additions to seq.v, ssrnat.v and order.v

### ISSUE THREAD

**Issue by MrSet** [math-comp/math-comp#505]
Hi,
I have been using math-comp for a while and have by doing so created a few lemmas which I thought might be useful for others than just me. 

I would like opinions on if you think that some of the Lemmas should be submitted in a PR. Before submitting such a PR I will, of course, try to make the naming-conventions and phrasings adhere to the `contributing.md` specifications. I have excluded proofs as I for the moment being only are interested in knowing whether you find the lemmas relevant or not. 

It might very well be that some of the content already is and math-comp and I simply have not been able to locate it. Any comments/suggestions are welcome!

### Addition of a find-first-option function
I suggest to add the following function to `seq.v` as right now there is only an indexing function to get the first element that fullfills a predicate from a list. Also, this function ensures that it is actually the *first* element that fulfills the predicate that is returned (i have founds this useful for constructing proofs).

```coq
Fixpoint findo {T : Type} (p : ssrbool.pred T) (s : seq T) :=
  if s is x :: xs then if p x then Some x else findo p xs else None.

Lemma findo_has {T : Type} (p : ssrbool.pred T) (s : seq T) :
  ((findo p s) : bool) = has p s.

Lemma perm_findo {T : eqType} (p : ssrbool.pred T) (s1 s2  : seq T):
  perm_eq s1 s2 -> (findo p s1 : bool) = (findo p s2 : bool). 

Lemma mem_findo {T : eqType} (p : ssrbool.pred T) (s1 s2  : seq T):
  s1 =i s2 -> (findo p s1 : bool) = (findo p s2 : bool). 

Lemma findoP {T : eqType} (p : ssrbool.pred T) (s : seq T) (x : T):
  reflect
    (exists s1 s2, s1 ++ [:: x] ++ s2 = s /\ p x /\ all (predC p) s1)
    ((Some x) == (findo p s)). 

Lemma findo_pred  {T : eqType} (p : ssrbool.pred T) (s : seq T) (x : T) :
  (findo p s) = Some x -> p x. 

Lemma findo_mem {T : eqType} (p : ssrbool.pred T) (s : seq T) (x : T) :
  Some x = findo p s -> x \in s. 
```
Also I suggest to add an function that finds the last element of a list that satisfies some predicate. 

```coq 
Definition rfindo {T : Type} (p : ssrbool.pred T) (s : seq T) :=
  findo p (rev s).

Lemma rfindo_has {T : Type} (p : ssrbool.pred T) (s : seq T) :
  ((rfindo p s) : bool) = has p s.

Lemma rfindoP {T : Type} (p : ssrbool.pred T) (s : seq T) :
  reflect
    (exists s1 s2 x, s1 ++ [:: x] ++ s2 = s /\ p x /\ all (predC p) s2)
    (rfindo p s).
```
### Subset lemmas
```coq
Lemma subset_trans {T : eqType} (s1 s2 s3  : seq T) :
  {subset s1 <= s2} -> {subset s2 <= s3} -> {subset s1 <= s3}.

Lemma subset_all {T : eqType} p (s1 s2 : seq T) :
  {subset s1 <= s2} -> all p s2 -> all p s1.

Lemma subset_cons {T : eqType} (s: seq T) (x : T):
  {subset s <= x:: s}. 

Lemma subset_cons2 {T : eqType} (s1 s2: seq T) (x : T):
  {subset s1 <= s2} -> {subset x::s1 <= x:: s2}. 

Lemma subset_catl {T : eqType} (s s': seq T):
  {subset s <= s' ++ s}. 

Lemma subset_catr {T : eqType} (s s': seq T):
  {subset s <= s' ++ s}. 

Lemma subset_cat2 {T : eqType} (s1 s2 s3: seq T):
  {subset s1 <= s2} -> {subset s3 ++ s1 <= s3 ++ s2}. 

Lemma filter_subset {T : eqType} p (s : seq T) :
  {subset [seq a <- s | p a] <= s}.

Lemma subset_filter {T : eqType} p (s1 s2 : seq T) :
  {subset s1 <= s2} -> {subset [seq a <- s1 | p a] <= [seq a <- s2 | p a]}.

Lemma map_subset {T1 T2 : eqType} (s1 s2 : seq T1) (f : T1 -> T2) :
  {subset s1 <= s2} -> {subset [seq f x | x <- s1 ] <= [seq f x | x <- s2]}. 
```

### Membership equality
```coq
Lemma map_mem_eq  {T A : eqType} (f : T -> A) (s1 s2 : seq T) :
  s1 =i s2 -> [seq f a | a <- s1 ] =i [seq f a | a <- s2]. 

Lemma filter_mem_eq {T : eqType} p (s1 s2 : seq T) :
  s1 =i s2 -> [seq a <- s1 | p a] =i [seq a <- s2 | p a]. 

```

### Various
All of these are fairly obvious but is handy to have when proving other stuff. 
```coq 
Lemma inP {T : eqType} (s : seq T) a :
  reflect (exists s' s'', s = s' ++ (a :: s'')) (a \in s).

Lemma map_map {A B C : Type} (f : A -> B) (g : B -> C) (s : seq A):
  [seq g x | x <- [seq f x | x <- s] ] = [seq g (f x) | x <- s]. 

Lemma cat_injr {T : Type} (s : seq T) : injective (cat s). 

Lemma cat_injl {T : Type} (s : seq T) : injective (cat^~ s). 

Lemma ohead_cat_some {T : Type} (a b : seq T) x :
  ohead a = Some x -> ohead a = ohead (a ++ b). 

Lemma all_count0 {T: Type} (p : ssrbool.pred T) (s : seq T):
  count p s == 0 = all (predC p) s.

Lemma perm_rem {T : eqType} (x : T) (s1 s2 : seq T) :
  perm_eq s1 s2 -> perm_eq (rem x s1) (rem x s2).

```
## Suggestions for `ssrnat.v`

These follow immediately by the corresponding lemmas for `ltn`, but I find them use to have specialized as these can easier be found by searching. 

```coq
Lemma gtn_trans : transitive gtn. 
Lemma gtn_irr : irreflexive gtn.
```
Also: Is there any reason why the irreflextivity lemma of `ltn` is named `ltnn` and does not use the `irreflexive` construction?

I also wondered if the following should be provided:
```coq
Lemma addn_injl n: injective (addn^~ n). 
Lemma addn_injr n: injective (addn n). 
```

I also wondered why there is a lemma called `leq_ltn_trans` but not the symmetric one: 
```coq
Lemma ltn_leq_trans n m p : m < n -> n <= p -> m < p. 
``` 

## Suggestions for `order.v`
I have also my self found it useful to have sequences of equality types as a meet-semi-lattice, ordered by the suffix-relation and with longest-common-suffix as meet. 

In general, I think that is reasonable to include the suffix predicate in `seq.v` (excluding the notation)?

```coq
Fixpoint suffix {T : eqType} (s1 s2 : seq T) : bool :=
  (s1 == s2) ||  if s2 is (x :: xs)
                then suffix s1 xs
                else false.

Lemma suffix_rec {T : eqType} (s1 s2 : seq T) : suffix s1 s2 = (s1 == s2) || suffix s1 s2. 

Notation "a ⪯ b" := (suffix a b) (at level 20).

Lemma suffix_refl {T : eqType} : reflexive (@suffix T).

Lemma suffixP {T : eqType} (s1 s2 : seq T) :
  reflect (exists xs, xs ++ s1 = s2) (s1 ⪯ s2). 

Lemma suffix_catl {T : eqType} (xs ys : seq T) :  xs ⪯ (ys ++ xs). 

Lemma suffix_trans {T : eqType} : transitive (@suffix T).

Lemma suffix_anti {T : eqType} : antisymmetric (@suffix T).

Lemma suffix_nil {T : eqType} (s : seq T) : [::] ⪯ s. 

Fixpoint lcs {T : eqType} (s1 s2 : seq T) : seq T :=
  if s1 ⪯ s2
  then s1
  else if s1 is x :: xs
       then lcs xs s2
       else [::]. 

Lemma lcs_suffix {T : eqType} (s1 s2 : seq T) :
  lcs s1 s2 ⪯ s1 && lcs s1 s2 ⪯ s2.

Lemma lcsP {T : eqType} (s s1 s2 : seq T) :
  s ⪯ s1 && s ⪯ s2 = s ⪯ lcs s1 s2.

Lemma lcsC {T : eqType} : commutative (@lcs T). 

Lemma lcsA {T : eqType} : associative (@lcs T). 

Lemma lcsss {T : eqType} : idempotent (@lcs T). 


```
Should I suggest this to #464 or make it a separate PR?

## Random
I often find my self trying to prove a goal of the form: `(true -> B) -> A`, where it somehow follows from the context that `B -> A`. In these situations, I find it useful to use the following lemma instead of doing `move/(_ (eq_refl true))` to get rid of the `true`. 

```coq
Lemma trueI (A : Type) : (true -> A) -> A. 
```

Also: I needed the following at some point and couldn't find it: 
```coq
Lemma predIC {T : Type} (p1 p2 : ssrbool.pred T):
  predI p1 p2 =1 predI p2 p1. 
```

**Comment by chdoc** [comment]
This is a long issue, so I will only address parts of it: 

- The rationale behind the definition of `find` is that returning an option makes if really awkward to use the result of find (cf. `nth_find` or `before_find`), because it moves the case analysis whether something was found from proofs to definitions. 
- I'm in favor adding `{subset _ <= _}` lemmas, but note that those lemmas that don't have subset assumptions have 2-step proofs using `mem_subseq` and the corresponding subseq lemmas. 

> Should I suggest this to #464 or make it a separate PR?

I think you should wait for one of the maintainers to comment. In any case, this is likely more than one pull request, and should not be mixed with any other pull requests.

**Comment by MrSet** [comment]
Thanks, for the feedback @chdoc. 

I do agree that it is not in all cases that `findo` is preferable to `find`, but I think that the library could provide both options as it does for `head` (and `ohead`). 
Particularly do I find it a bit clumsy to state that the element that a combination of `find` and `nth` in fact is the first element that fulfills the predicate in this list.

**Comment by chdoc** [comment]
The rationale for `head` and `ohead` is that `seq T` is inhabited even if `T` is empty. So a default may not always be available.

Indeed, I had overlooked that your `findo` returns the found element rather than its index. Maybe call it `first` and define it as `ohead \o filter p`?

Still, assuming there is a default element around, I would opt for using `nth` and `find`. If you only need to split at the first element in proofs, one can use (taken from one of my developments)
```coq
Lemma split_at_first (T : eqType) (A : pred T) (p : seq T) : 
    has A p -> exists z p1 p2, [/\ p = p1 ++ z :: p2, z \in A & ~~ has A p1].
Proof.
  move => hasA; have [k kp kA] := hasP hasA.
  pose n := find A p.
  pose p1 := take n p; pose p2 := drop n.+1 p; pose z := nth k p n.
  exists z; exists p1; exists p2; rewrite /p1 /p2 /z unfold_in nth_find // take_find.
  by split => //; rewrite -drop_nth -?has_find ?cat_take_drop.
Qed.
```
For reasoning about computations involving `find`, I would introduce a variant type and prove a case lemma (along the lines of `path.split` `path.splitP`) replacing the definitions of `p1`, `p2` and `z`, should they occur in the goal.

**Comment by MrSet** [comment]
Good point about `head` and `ohead`, I didn't think of that. 

Regarding defining `findo` as `ohead \o filter p`. Yes it could be done that way. I find however that it is a bit unnatural to define it this way, as the work that filter does on the rest of the list - somehow seems wasted (I know that this is a matter of taste as optimizing coq code still has a long way to go). Also, other functions could have been defined in terms of `filter` but have been defined in a more "natural" way instead. An example is `count p` which could be defined as `size \o filter p`. 

I agree it could be an option to have such a lemma instead. I somehow convinced my self that it was more in the spirit of the library to define it computationally. But definitely: A lemma such as the one you provide could be a useful addition instead of the definitional version (btw. I think that `take_find` may be another addition useful in `seq.v`?).

**Comment by chdoc** [comment]
> btw. I think that `take_find` may be another addition useful in `seq.v`?).
Yes, that's on my list to PR eventually. When I posted the proof, I forgot that it's not in there already.

**Comment by CohenCyril** [comment]
Hi @MrSet and thank you for taking the time to submit this. I'm glad that you have been using the math-comp library and that you are willing to improve. I only gave one quick look to your suggestions, but I will try to comment right now and come back later.

I will start with 
> ## Suggestions for `seq.v`
> ### Addition of a find-first-option function

and answer on other points another day.

In https://github.com/math-comp/math-comp/issues/505#issuecomment-627913638, you write:

> Particularly do I find it a bit clumsy to state that the element that a combination of `find` and `nth` in fact is the first element that fulfills the predicate in this list.

1. From an efficiency point of view, I can understand (you go through the list twice and if the element is not in, the second pass goes through the entire list before defaulting), however from a theoretical point of view, you get strictly more information by knowing first the index, and then finding the argument (e.g. `index` is a particular case of `find`). What might be unsettling is that the naming choice is not the same as in haskell or ocaml for example, but to each library its conventions, so if it stays in one form or another, `ofind` should be renamed (`ofind_mem` or something). And since it can be expressed in other terms (as @chdoc noted) the minimal interface should provide translation lemmas (e.g. `ofind_mem p s = ohead (filter p s)`)

2. We tend to pick one predicate as a canonical way to express something and make all lemmas use it. In this case `has` is the canonical way to denote existence of an element satisfying the predicate, and should replace every test of `ofind` as a boolean (except for the equality `ofind p s = has p s :> bool`).

3. Using an option type is in most cases not so interesting, because invariants are usually assured by proofs and we do not have a good monad (/monad transformer) system to handle them while programming. I suspect, lemmas such as `findoP`, `findo_pred`, `findo_mem` require a heavy preprocessing before they can be applied... in some way you immediately "go out of the monad" when you use them. Hence it is often more usable to have a "default" version. e.g. `T -> pred T -> seq T -> T` where the first argument is a default value. (You can always recover the default by lifting with `Some`). And the equlivalence is  `find_mem x0 p s = head x0 (filter p s) = nth x0 s (find p s)`...
And then, does your efficiency problem really requires the addition of this new find functions?

In the end the best way to decide is to see usecases, and see if the points I wrote above tend to simplify or complexify the proofs. Would you mind sharing?

**Comment by pi8027** [comment]
> ## Suggestions for `ssrnat.v`
> These follow immediately by the corresponding lemmas for `ltn`, but I find them use to have specialized as these can easier be found by searching.
> 
> ```coq
> Lemma gtn_trans : transitive gtn. 
> Lemma gtn_irr : irreflexive gtn.
> ```

Since `gtn n m` is convertible to `m < n`, we can rather use `ltn_trans` and `ltnn`. But if there are any use cases that `ltn_trans` and `ltnn` are not applicable, I would like to see.

> Also: Is there any reason why the irreflextivity lemma of `ltn` is named `ltnn` and does not use the `irreflexive` construction?

I think that the name is fine but it is better to use `irreflexive`.

> I also wondered if the following should be provided:
> 
> ```coq
> Lemma addn_injl n: injective (addn^~ n). 
> Lemma addn_injr n: injective (addn n). 
> ```

There are `addnI : right_injective addn` and `addIn : left_injective addn` in ssrnat.

> I also wondered why there is a lemma called `leq_ltn_trans` but not the symmetric one:
> 
> ```coq
> Lemma ltn_leq_trans n m p : m < n -> n <= p -> m < p. 
> ```

We don't need `ltn_leq_trans` because it is an instance of `leq_trans` (`m < n` is defined as `m.+1 <= n`).

**Comment by MrSet** [comment]
Thank you for the feedback/explanations @pi8027. 

> Since `gtn n m` is convertible to `m < n`, we can rather use `ltn_trans` and `ltnn`. But if there are any use cases that `ltn_trans` and `ltnn` are not applicable, I would like to see.

I came across it when sorting in descending order and afterwards using the lemmas about `sort` (an example is `sorted_uniq`)  which often leaves you with a goal `transitive gtn`. I know that `transitive gtn` can easily be derived from `ltn_trans`, but I think that this should be closed with just a single `apply` (or ideally just providing the argument directly to `sorted_uniq`), which I don't think it can without introductions using only `ltn_trans`. 

I do however see that `apply/ltnn` directly closes a goal of the form `irreflexive gtn`, so `gtn_irr` is definitely not needed i see. Using `irreflexive` in the definition of `ltnn` would also improve searchability for the lemma.

> There are `addnI : right_injective addn` and `addIn : left_injective addn` in ssrnat.

Thanks, I have simply not found these. Which might hint at a different problem - namely the searchability for these lemmas. It seems like there is some inconsistency in how these things are defined/naming_conventions in the library that makes it hard to search for.
`right_injective` and `left_injective` are only used for `addn` and `addb`, whereas in `seq. v` is the following lemmas provided for `rcons`. 
```coq
Lemma rcons_injl x : injective (rcons^~ x).
Lemma rcons_injr s : injective (rcons s).
```
> We don't need `ltn_leq_trans` because it is an instance of `leq_trans` (`m < n` is syntactically equal to `m.+1 <= n`).

I see! Thanks!

**Comment by MrSet** [comment]
Thank you for the feedback/explanations @CohenCyril.

> 2. We tend to pick one predicate as a canonical way to express something and make all lemmas use it. In this case `has` is the canonical way to denote existence of an element satisfying the predicate, and should replace every test of `ofind` as a boolean (except for the equality `ofind p s = has p s :> bool`).

That seems like a reasonable approach to take. I guess this hints at that a lemma similar to what @chdoc provided with `split_at_first` earlier would be a usefull edition to `seq.v`?
This will also be enough for my use-cases (as I only use this construction inside proofs). 

> 3. Using an option type is in most cases not so interesting, because invariants are usually assured by proofs and we do not have a good monad (/monad transformer) system to handle them while programming. I suspect, lemmas such as `findoP`, `findo_pred`, `findo_mem` require a heavy preprocessing before they can be applied... in some way you immediately "go out of the monad" when you use them. Hence it is often more usable to have a "default" version. e.g. `T -> pred T -> seq T -> T` where the first argument is a default value. (You can always recover the default by lifting with `Some`). And the equlivalence is  `find_mem x0 p s = head x0 (filter p s) = nth x0 s (find p s)`...
>    And then, does your efficiency problem really requires the addition of this new find functions?
> 
> In the end the best way to decide is to see usecases, and see if the points I wrote above tend to simplify or complexify the proofs. Would you mind sharing?

I have no use-case where efficiency is required - only used the construction in proofs and thought that I might as well define it as a function as it seemed like something I would expect to find in a library. 
I see that there are quite some advantages defining it with a default element, which is more than fine with me.

**Comment by chdoc** [comment]
I thought a bit more about the `split_at_first` thing and I proved the `Variant` version I had alluded to earlier:
```coq
Variant split_at_first (T : eqType) (p : pred T) : seq T -> seq T -> T -> seq T -> Type :=
  SplitAtFirst z s1 s2 of p z & ~~ has p s1 : split_at_first p s1 s2 z (rcons s1 z ++ s2).

Lemma split_at_firstP (T : eqType) (x : T) (p : pred T) (s : seq T) : 
  has p s -> 
  let n := find p s in split_at_first p (take n s) (drop n.+1 s) (nth x s n) s.
Proof.
move => hasA; pose n := find p s.
pose s1 := take n s; pose s2 := drop n.+1 s; pose z := nth x s n.
rewrite -{5}[s](cat_take_drop n) [drop n _](drop_nth x) -?has_find //. 
rewrite -cat1s catA cats1; by constructor; [exact: nth_find|exact: take_find].
Qed.
```
with `x : T` and `hasA : has A s`, this can be used as  `case def_s : _ /(split_at_firstP x hasA) => [z s1 s2 ...].` where `def_s` is the equation for `s`. The case will also replace all occurrences of `s` with `rcons s1 z ++ s2` and `nth x s (find A s)`, `take (find A s) s` and `drop (find A s).+1 s` with the variables introduced. With a second `_`, `def_s` becomes the equation for `nth ...` instead. This is inspired by `path.splitP`.

@MrSet Maybe you can try to use it and see whether that's the right lemma for your proofs?

**Comment by MrSet** [comment]
@chdoc, Thank you for taking the time to show me this. I didn't know if this "trick" before so thanks a lot!

The lemma is close to being very useful in the proofs I am doing. I do however find it slightly annoying that you need to provide the element `x : T` in order to use the lemma, as this will never be used in the conclusion (only as a default element for nth, but this will again never be used), and it is not always that you have such a an element by hand. 

I find it helpful to have another version (I also found inspiration in `path.v`) as well (when no indices is needed): 

```coq
Variant split_at_firstr (T : eqType) (p : ssrbool.pred T) : seq T -> Prop :=
  SplitAtFirstr z s1 s2 of p z & ~~ has p s1 : split_at_firstr p (s1  ++ z :: s2).

Lemma split_at_firstPr (T : eqType) (p : ssrbool.pred T) (s : seq T) : 
  has p s -> split_at_firstr p s.
Proof.
move=> hasA. move/hasP: (hasA)=> [] ?.
by case/split_at_firstP: hasA => //= >; rewrite cat_rcons. 
Qed. 
```

**Comment by chdoc** [comment]
Sure, your version is a useful simplified variant. The lemma I provided aims to be as general as possible. If you want to replace an "`nth ... find`, the default in the lemma must match the default in the goal. But I agree, it's annoying when not used.

**Comment by CohenCyril** [comment]
@chdoc @MrSet I suggest the following compromise of your `Variant`:
```coq
Variant find_split (T : Type) (p : pred T) : seq T -> seq T -> seq T -> Type :=
  FindSplit z s1 s2 of p z & ~~ has p s1 :
    find_split p (rcons s1 z ++ s2) s1 s2.

Lemma find_splitP {T : Type} (p : pred T) (s : seq T) (i := find p s) :
  has p s -> find_split p s (take i s) (drop i.+1 s).
```
That is actually the compromise made by `splitP` which does not require an extra `x : T` (and thus works with the empty list for an abstract `T`) and where `s` comes as first index (to favor matching on `take` and `drop`). Note this lemma can and should be generalized to any `Type`.

**Comment by CohenCyril** [comment]
We could also have the "default" variant though... and a complement lemma just in case:
```coq
Lemma has_take {T : Type} (p : pred T) (s : seq T) i : has p s ->
  has p (take i s) = (find p s < i).
Proof.
by elim: s i => [|y s ihs] [|i]//=; rewrite ?inE/=; case: (p _) => // /ihs->.
Qed.

Lemma in_take {T : eqType} (s : seq T) x i : x \in s ->
  (x \in take i s) = (index x s < i).
Proof. by move=> xs; rewrite -has_take ?has_pred1. Qed.

Variant dflt_find_split (T : Type) (p : pred T) :
    seq T -> T -> seq T -> seq T -> Type :=
  DfltFindSplit z s1 s2 of p z & ~~ has p s1 :
    dflt_find_split p (rcons s1 z ++ s2) z s1 s2.

Lemma dflt_find_splitP {T : Type} x0 (p : pred T) (s : seq T) (i := find p s) :
  has p s -> dflt_find_split p s (nth x0 s i) (take i s) (drop i.+1 s).
Proof.
move=> p_x; rewrite -[X in dflt_find_split _ X](cat_take_drop i s).
rewrite (drop_nth x0 _) -?has_find// -cat_rcons.
by constructor; [apply: nth_find | rewrite has_take// ltnn].
Qed.

Variant find_split (T : Type) (p : pred T) : seq T -> seq T -> seq T -> Type :=
  FindSplit z s1 s2 of p z & ~~ has p s1 :
    find_split p (rcons s1 z ++ s2) s1 s2.

Lemma find_splitP {T : Type} (p : pred T) (s : seq T) (i := find p s) :
  has p s -> find_split p s (take i s) (drop i.+1 s).
Proof.
case def_s : {-}s => [|x s'] in @i *; first by rewrite def_s.
by move=> hps; case: (@dflt_find_splitP _ x) => //; constructor.
Qed.

Lemma nth_take_find_drop {T : Type} x0 (p : pred T) (s1 s2 : seq T) z 
  (s := rcons s1 z ++ s2) : p z -> ~~ has p s1 -> nth x0 s (find p s) = z.
Proof.
move=> pz pNs1; rewrite /s  cat_rcons find_cat (negPf pNs1).
by rewrite nth_cat/= pz addn0 subnn ltnn.
Qed.
```

**Comment by pi8027** [comment]
> > Since `gtn n m` is convertible to `m < n`, we can rather use `ltn_trans` and `ltnn`. But if there are any use cases that `ltn_trans` and `ltnn` are not applicable, I would like to see.
> 
> I came across it when sorting in descending order and afterwards using the lemmas about `sort` (an example is `sorted_uniq`) which often leaves you with a goal `transitive gtn`. I know that `transitive gtn` can easily be derived from `ltn_trans`, but I think that this should be closed with just a single `apply` (or ideally just providing the argument directly to `sorted_uniq`), which I don't think it can without introductions using only `ltn_trans`.

I see. Let me suggest another solution. Some sorting related lemmas specialized to `orderType` are also available in the order library. You may use them with dual ordering, e.g.,
```coq
Import Order.Theory.

Check (@sort_le_sorted _ [orderType of nat^d]).
(*
sort_le_sorted
     : forall s : seq [orderType of nat^d], sorted <=^d%O (sort <=^d%O s)
*)
Check (fun s : seq nat^d => sort_le_sorted s).
(*
[eta sort_le_sorted]
     : forall s : seq nat^d, sorted <=^d%O (sort <=^d%O s)
*)
```
where `<=^d%O` means `geq` here. Unfortunately, many lemmas including `sorted_uniq` are missing in order.v, but we can add them anyway.

> > There are `addnI : right_injective addn` and `addIn : left_injective addn` in ssrnat.
> 
> Thanks, I have simply not found these. Which might hint at a different problem - namely the searchability for these lemmas. It seems like there is some inconsistency in how these things are defined/naming_conventions in the library that makes it hard to search for.
> `right_injective` and `left_injective` are only used for `addn` and `addb`, whereas in `seq. v` is the following lemmas provided for `rcons`.
> 
> ```coq
> Lemma rcons_injl x : injective (rcons^~ x).
> Lemma rcons_injr s : injective (rcons s).
> ```

I think it's better and also safe to use `left_injective` and `right_injective` for those `rcons` lemmas. Let me prepare a PR.

**Comment by chdoc** [comment]
@MrSet Now that #567, the part that's been discussed at length there here so far, has been merged, would you be okay with closing this issue and reopening issues (or pull requests) for other groups of lemmas, so that each can receive an independent proper discussion?
