### ISSUE TITLE
mem_imset mem_map naming/statement inconsistency

### ISSUE THREAD

**Issue by chdoc** [math-comp/math-comp#508]
while cleaning, I noticed the following oddity:
```coq
Lemma mem_imset (aT rT : finType) (f : aT -> rT) (D : {pred aT}) (x : aT) : 
  x \in D -> f x \in [set f x | x in D]

Lemma map_f (T1 T2 : eqType) (f : T1 -> T2) (s : seq T1) (x : T1) : 
   x \in s -> f x \in [seq f i | i <- s]
Lemma mem_map (T1 T2 : eqType) (f : T1 -> T2),
  injective f -> forall (s : seq T1) (x : T1), (f x \in [seq f i | i <- s]) = (x \in s)
```
Wouldn't it be more consistent to rename `mem_imset` to `imset_f` and add the following lemma:
```coq
Lemma mem_imset (aT rT : finType) (f : aT -> rT) (A : {set aT}) (x : aT) :
  injective f -> (f x \in f @: A) = (x \in A).
```

**Comment by chdoc** [comment]
This change is going to break a lot of proofs. There are almost 100 uses of `mem_imset` in mathcomp and I don't know how many in the CI (and dependent developments).

So what would be the procedure to fix something like this? What's been done in the past?

**Comment by pi8027** [comment]
We can use the `deprecate` notation to fix that properly as in #473.

**Comment by chdoc** [comment]
As long as the current `mem_imset` is deprecated, its replacement cannot be added under the same name. So what's would be the plan?

1. deprecate `mem_imset`, add `imset_f` (same type) and add `mem_imset_eq` (the second `mem_imset` above)
2. Remove the deprecated `mem_imset`, deprecate `mem_imset_eq` in favor or the new `mem_imset`
3. Remove the "intermediate" `mem_imset_eq`

That would take three releases for a rather innocent change. On the other hand, causing disruptions for something this minor is also not great. @CohenCyril , how has this type of issue been handled in the past?

**Comment by CohenCyril** [comment]
> That would take three releases for a rather innocent change. On the other hand, causing disruptions for something this minor is also not great. @CohenCyril , how has this type of issue been handled in the past?

For me this is the tupical usecase for a compatibility module mc_1_11_0 that you import when you want to restore previous behaviour for a while... however this does not allow cross compatibility like deprecation does but it allows for more flexibility in porting code. I guess for cross compatibility, we should have "future behaviour" features rather than "previous behaviour" (or make sure the "previous behavior" module always exist even when they are empty).

**Comment by chdoc** [comment]
I think this kind of small change should not be the reason for breaking cross compatibility.

**Comment by CohenCyril** [comment]
Yep, but these changes might accumulate and we might end up with several breaking cross compatibility (e.g. #492 already pertains to this category) and this could become unmanageable. We really need to work out a discipline for that (even if it ends up being a sed script).

**Comment by chdoc** [comment]
Maybe this is something to be discussed in one of the upcoming mathcomp meetings?

**Comment by CohenCyril** [comment]
> Maybe this is something to be discussed in one of the upcoming mathcomp meetings?

Yes, added the topic to the MeetingTopics

**Comment by chdoc** [comment]
According to the mathcomp meeting from 30.6.2020, the roadmap for this issue is:

> * 1.12.0 : deprecate `mem_imset`, add `imset_f` (same type) and add `mem_imset_eq` (the second `mem_imset` above)
> 
> * 1.13.0 : Remove the deprecated `mem_imset`, deprecate `mem_imset_eq` in favor or the new `mem_imset`
> 
> * 1.14.0 : Remove the "intermediate" `mem_imset_eq`

While doing [the first part](https://github.com/math-comp/math-comp/compare/master...chdoc:mem-imset) , I noticed that there is also:

```coq
mem_imset2 : forall (aT aT2 rT : finType) (f2 : aT -> aT2 -> rT) (D : predPredType aT) (D2 : aT -> predPredType aT2)
         (x : aT) (x2 : aT2), x \in D -> x2 \in D2 x -> f2 x x2 \in [set f2 x y | x in D, y in D2 x]
```
Should this become `imset2_f` by the same rationale, even though there is no version for `injective` for functions in two arguments?

**Comment by CohenCyril** [comment]
> Should this become `imset2_f` by the same rationale, even though there is no version for `injective` for functions in two arguments?

I guess so...
