### ISSUE TITLE
lemma for proper and setC?

### ISSUE THREAD

**Issue by chdoc** [math-comp/math-comp#512]
I noticed that there are quite a few lemmas combining `_ \subset _` and `~: _` but none for
 `_ \proper _` and `~: _`. 

How about adding (possibly with a different name):
```coq
Lemma properC (T : finType) (A B : {set T}) : A \proper B = (~: B \proper ~: A).
Proof. 
rewrite !properEneq setCS [~: _ == _]inj_eq 1?eq_sym //; exact/inv_inj/setCK.
Qed.
```
I think this is sufficient, since any introduced double complement can easily be eliminated with `?setCK`.

**Comment by chdoc** [comment]
To be more specific, for `_ \subset _` and `~: _` there is:
```coq
setCS: forall (T : finType) (A B : {set T}), (~: A \subset ~: B) = (B \subset A)
subsetC: forall (T : finType) (A B : {set T}), (A \subset ~: B) = (B \subset ~: A)
subCset: forall (T : finType) (A B : {set T}), (~: A \subset B) = (~: B \subset A)
```
All three of them also hold for proper, but what would be the appropriate names?

**Comment by CohenCyril** [comment]
@chdoc That's actually the one question: what should be the names. It should be in line with current similar lemmas. I can find two occurences with two distinct conventions (sadly :crying_cat_face:)
There is on one side: https://github.com/math-comp/math-comp/blob/3728862662bd0a5b836dfa746921954604d051ec/mathcomp/algebra/ssrnum.v#L1592-L1612
and on the other side https://github.com/math-comp/math-comp/blob/3728862662bd0a5b836dfa746921954604d051ec/mathcomp/ssreflect/order.v#L4272-L4277  https://github.com/math-comp/math-comp/blob/3728862662bd0a5b836dfa746921954604d051ec/mathcomp/ssreflect/order.v#L4309-L4313

**Comment by chdoc** [comment]
Well, `subsetC` and `subCset` are (sort of) in the second category. Except that `subset` can be reasonably split into `sub` and `set`. But while `properCset` might work, I'm unsure about `propersetC` or `proper_setC`. And I don't know why `setCS` is named as it is, so I don't know whats the `proper` version. :man_shrugging:

**Comment by CohenCyril** [comment]
I would opt for `properC`, `properCr`, `properCl`...

**Comment by CohenCyril** [comment]
> why `setCS` is named as it is, so I don't know whats the `proper` version.

`set` is the generic prefix for `set` operators, `C` is for `complement` and `S` for `subset` (as in `setSI`, `setIS`, etc where the side of `S` wrt `I` denotes which  side to "forget", which makes no sense for `C` since there is no "side" so to speak) ... However there is no assigned suffix for `proper`, so no way to do the same as `subset` unless we assign one...
