### ISSUE TITLE
max and min are too specific

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#515]
From 1.10 to 1.11+beta1 we lost in generality in ``ssrnum.v``: indeed ``max`` and ``min`` where defined in a ``numDomainType``, but they are now defined in terms of  ``meet`` and ``join``, which requires at least lattice, which a ``numDomainType`` is not...

One possible fix is to reintroduce ``Order.max`` (and ``Order.min``) as ``if x <= y then y else x`` (and similar for min), and develop their theory in a partial order, when elements are all comparable between themselves. Then link them with meet and join when appropriate.

Another fix is to reintroduce ``Num.max`` and ``Num.min`` but this would be confusing if we keep ``Order.min`` and ``Order.max``.

In any case these definitions must match exactly the one that existed in 1.10.0 for backward compatiblity reasons and the equations given in the factories for total order (which should be updated if they do not match).

**Comment by CohenCyril** [comment]
I barely started doing this a few days ago and if someone is interested in doing it, we can talk.

**Comment by affeldt-aist** [comment]
The fix with `Order.max` and the fix with `Num.max` are exclusive fixes?

**Comment by CohenCyril** [comment]
> The fix with `Order.max` and the fix with `Num.max` are exclusive fixes?

Yes
