### ISSUE TITLE
Notations `dual_(bottom|top|join|meet|max|min)` should be qualified by the `Order` module

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#538]
https://github.com/math-comp/math-comp/blob/f25ef67ad2f58a30f1e700da89811b193755d84e/mathcomp/ssreflect/order.v#L2541-L2546

Since `Order.bottom`, etc. are qualified, I thought they should, but actually they are not. @CohenCyril

**Comment by CohenCyril** [comment]
Good point, this is definitely an issue.

**Comment by pi8027** [comment]
Let me finish #494 first. Then I will fix this.
