### ISSUE TITLE
Missing "rquot_comRingType" exported.

### ISSUE THREAD

**Issue by kik** [math-comp/math-comp#56]
I think "rquot_comRingType" in here

https://github.com/math-comp/math-comp/blob/cd072f48cf929d7d7f9170d3348ca44a4802a511/mathcomp/algebra/ring_quotient.v#L616

should be exported at

https://github.com/math-comp/math-comp/blob/cd072f48cf929d7d7f9170d3348ca44a4802a511/mathcomp/algebra/ring_quotient.v#L649

**Comment by CohenCyril** [comment]
Thanks for this comment. This is fixed now.
