### ISSUE TITLE
Spacing convention before `//`

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#580]
When should we write `thm//` and when should we write `thm //`?
Clarify, document in `CONTRIBUTING.md` and uniformize the library.

**Comment by CohenCyril** [comment]
This was discussed and answered in [September 9, 2020 Mathcomp meeting](https://github.com/math-comp/math-comp/wiki/Minutes-September-09-2020)

**Comment by affeldt-aist** [comment]
It looks like users are now using `?lem//` to say that this is the subgoals generated by this rewriting that are discharged so the number of characters is not the only criterion anymore.
NB: There is no change of semantics with or without space.
