### ISSUE TITLE
Does one use `matrix` or `mx`?

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#581]
> Specially when does one use `matrix` or `mx`

There are actually very few (10) theorems, one notation and zero definition (except for `matrix` itself which is only used with the notation `'M_(_, _)`) with `matrix` as a substring, 
- `matrixP`, `row_matrixP`, `matrix_sum_delta`, `card_matrix`,`matrix_eq0`, `matrix0Pn`, `matrix_nonzero1`, `matrix_modl`, `matrix_modr` and `gal_matrix`
- and `\matrix_...`.

I believe we could rename all the lemmas to use `mx` instead of `matrix`.
EDIT: (I do not suggest to change `\matrix_`)

_Originally posted by @CohenCyril in https://github.com/math-comp/math-comp/pull/577#discussion_r484593596_

**Comment by CohenCyril** [comment]
FTR: this has been discussed in the [last mathcomp meeting](https://github.com/math-comp/math-comp/wiki/Minutes-September-23-2020)

**Comment by CohenCyril** [comment]
Actually, I'd like to backtrack on this... I am really not convinced by the resulting PR #652

**Comment by CohenCyril** [comment]
At the last mathcomp meeting (2021-06-02) we decide to perform the renaming only for the suffix `card_mx`

**Comment by thery** [comment]
@CohenCyril  Following the rule of suffix, should we also rename `row_matrixP` and into `row_mxP`
also I've discovered `submxrow_matrix`  but I don't understand the naming of this one. For me,
it should be `submxrow_block` or something like that
