### ISSUE TITLE
Missing contra lemmas

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#587]
AFAIK, the following are still missing:
```coq
Lemma contra_not_neq P x y : (x = y -> P) -> ~ P -> x != y.
Lemma contra_eq_not P x y : (P -> x != y) -> x = y -> ~ P.
```
(@chdoc I did not notice the first time)

**Comment by chdoc** [comment]
I guess this just reinforces the point that one needs a lot of lemmas to cover all the cases, even if one treats "only" equality, nat comparison and general orders specially ...
