### ISSUE TITLE
Bump CeCILL-B version

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#595]
context: https://coq.zulipchat.com/#narrow/stream/250632-Coq-Platform.20devs.20.26.20users/topic/Coq.20platform.208.2E12.2E0.2Bbeta1.20released

Apparently we are using a version of CeCILL that contains some commas that are a bit controversial. Bumping the license to the latest version, which seems to be something anyone has the right to do anyway, would clear these issues.

This is likely material for the next call. CC @MSoegtropIMC @Zimmi48

**Comment by chdoc** [comment]
Following the realization that there is only one version of CeCILL-B, I guess this issue can be closed.
