### ISSUE TITLE
rename `mem_imset_eq` and `mem_imset2_eq` and remove deprecation aliases

### ISSUE THREAD

**Issue by chdoc** [math-comp/math-comp#602]
This is a cleanup issue. Following the merging of #592 , it remains to:

- remove the deprecation aliases for `mem_imsert` and `mem_imset2`
- rename `mem_imset_eq` -> `mem_imset`
- rename `mem_imset2_eq` -> `mem_imset2`
- create deprecation aliases for `mem_imset_eq` and `mem_imset2_eq`

**Comment by CohenCyril** [comment]
Fixed by #749
