### ISSUE TITLE
Coq 8.4, 8.5, 8.6 : issues with ssrpattern and ssrpatternarg(pat) 

### ISSUE THREAD

**Issue by erikmd** [math-comp/math-comp#62]
Hello,
I've experimented the ssrpattern tactic with MathComp for Coq 8.4, 8.5, and 8.6, and I believe that the behavior/syntax of this tactic is not uniform across the versions of SSReflect.

**EDIT**: Below is an update of my report that relies on MathComp 1.6.1 for Coq 8.5 and 8.6.
Here is my setup:
- OCaml 4.02.3, Coq 8.5pl2, MathComp 1.6.1
- OCaml 4.02.3, Coq 8.6, MathComp 1.6.1

My report relies on the following test file:

``` coq
Require Import mathcomp.ssreflect.ssreflect mathcomp.ssreflect.seq.
(* 1 *) From mathcomp (* ONLY FOR Coq 8.5 *)
Require Import ssrmatching.
(* 2 *) Declare ML Module "ssreflect". (* ONLY FOR Coq 8.5, cf. issue #61 *)
Tactic Notation "ssrpat" ssrpatternarg(pat) := ssrpattern pat.
Tactic Notation "ssrrew" ssrpatternarg(pat) :=
  rewrite [pat](eq_from_nth (x0 := 0) (s2 := [:: 99])).

Goal [::] = [::] :> list nat.
(* 3 *) ssrpattern RHS.

Goal [::] = [::] :> list nat.
(* 4 *) ssrpat RHS.

Goal [::] = [::] :> list nat.
(* 5 *) ssrrew RHS.

Goal [::] = [::] :> list nat.
(* 6 *) ssrpattern (X in _ = X).

Goal [::] = [::] :> list nat.
(* 7 *) ssrpat (X in _ = X).

Goal [::] = [::] :> list nat.
(* 8 *) ssrrew (X in _ = X).
```

Here is the summary of what I obtained:
- Coq 8.6: everything compiles, if one removes Line 1 and Line 2 (which is a [workaround for Coq 8.5](https://github.com/math-comp/math-comp/issues/61)).
- Coq 8.5:
  - [ ] Line 3 raises "Error: RHS is bound to a notation that does not denote a reference."
  - [ ] Line 5 raises "Error: variable pat should be bound to a term."
  - [ ] Lines 6, 7, 8 raise "Error: Unknown interpretation for notation "( _ in _ )"."

Best,
Erik

**Comment by gares** [comment]
Needs to be reviewed since 1.6.1 should have aligned 8.5 and 8.6 on the syntax of ssrpattern

**Comment by erikmd** [comment]
Hi @gares, indeed I have to retest this with MathComp 1.6.1... I'm going to do this ASAP. Kind regards.

**Comment by erikmd** [comment]
Hi @gares, sorry for the delay of my reply.
I have installed MathComp 1.6.1 with both Coq 8.5pl2 and Coq 8.6 and I confirm that there is still some issue regarding ssrpattern and/or ssrpatternarg for Coq 8.5.
I have just edited the description of this issue for updating my test cases.
Best regards.

**Comment by erikmd** [comment]
Hi @gares 
FYI this issue is still reproducible with Coq 8.5.3 and MathComp 1.6.4

**Comment by CohenCyril** [comment]
None of the versions of Coq mentioned in the title are supported by math-comp anymore. Feel free to reopen the issue if needed.
