### ISSUE TITLE
Missing lemmas of membership equality

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#620]
```coq
Lemma map_mem_eq  {T A : eqType} (f : T -> A) (s1 s2 : seq T) :
  s1 =i s2 -> [seq f a | a <- s1 ] =i [seq f a | a <- s2]. 

Lemma filter_mem_eq {T : eqType} p (s1 s2 : seq T) :
  s1 =i s2 -> [seq a <- s1 | p a] =i [seq a <- s2 | p a].
```

_Originally posted by @MrSet in https://github.com/math-comp/math-comp/issues/505#issue-617258774_

**Comment by CohenCyril** [comment]
I'm in favor, but I'd name them `eq_mem_map` and `eq_mem_filter`.

**Comment by chdoc** [comment]
There is also some equality lemmas missing, such as
```coq
Lemma eq_in_pmap (aT : eqType) rT (f1 f2 : aT -> option rT) (s : seq aT) : 
  {in s, f1 =1 f2} -> pmap f1 s = pmap f2 s.
```
and possibly the variant without `in`. Moreover, the proofs of these lemmas and (and any other lemmas with `{in s, _}` assumptions that are proved by induction on `s` might be simplified by adding the following helper lemma:
```coq
Lemma forall_cons (T : eqType) (P : T -> Prop) a (s : seq T) : 
  {in a::s, forall x, P x} <-> P a /\ {in s, forall x, P x}.
Proof.
split => [A|[A B]]; last by move => x /predU1P [-> //|]; apply: B.
by split => [|b Hb]; apply: A; rewrite !inE ?eqxx ?Hb. 
Qed.
```
Any other lemmas in the same vein that are missing?
