### ISSUE TITLE
Sequences ordered by the suffix-relation

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#621]
I have also my self found it useful to have sequences of equality types as a meet-semi-lattice, ordered by the suffix-relation and with longest-common-suffix as meet.

In general, I think that is reasonable to include the suffix predicate in `seq.v` (excluding the notation)?

```coq
Fixpoint suffix {T : eqType} (s1 s2 : seq T) : bool :=
  (s1 == s2) ||  if s2 is (x :: xs)
                then suffix s1 xs
                else false.

Lemma suffix_rec {T : eqType} (s1 s2 : seq T) : suffix s1 s2 = (s1 == s2) || suffix s1 s2. 

Notation "a ⪯ b" := (suffix a b) (at level 20).

Lemma suffix_refl {T : eqType} : reflexive (@suffix T).

Lemma suffixP {T : eqType} (s1 s2 : seq T) :
  reflect (exists xs, xs ++ s1 = s2) (s1 ⪯ s2). 

Lemma suffix_catl {T : eqType} (xs ys : seq T) :  xs ⪯ (ys ++ xs). 

Lemma suffix_trans {T : eqType} : transitive (@suffix T).

Lemma suffix_anti {T : eqType} : antisymmetric (@suffix T).

Lemma suffix_nil {T : eqType} (s : seq T) : [::] ⪯ s. 

Fixpoint lcs {T : eqType} (s1 s2 : seq T) : seq T :=
  if s1 ⪯ s2
  then s1
  else if s1 is x :: xs
       then lcs xs s2
       else [::]. 

Lemma lcs_suffix {T : eqType} (s1 s2 : seq T) :
  lcs s1 s2 ⪯ s1 && lcs s1 s2 ⪯ s2.

Lemma lcsP {T : eqType} (s s1 s2 : seq T) :
  s ⪯ s1 && s ⪯ s2 = s ⪯ lcs s1 s2.

Lemma lcsC {T : eqType} : commutative (@lcs T). 

Lemma lcsA {T : eqType} : associative (@lcs T). 

Lemma lcsss {T : eqType} : idempotent (@lcs T). 
```

_Originally posted by @MrSet in https://github.com/math-comp/math-comp/issues/505#issue-617258774_

**Comment by pi8027** [comment]
IIUC, these `porderType` instances for the prefix- and suffix-relations can be derived using the (reverse) lexicographic ordering and a trivial `porderType` instance defined by `(x <= y) := (x == y)`.

**Comment by chdoc** [comment]
I find the argument order of `suffix` counterintuitive, I would expect `suffix s` to be the ambivalent predicate of suffixes of `s`, in particular since one can write `p \in suffix s` (cf. `connect`). Also, I'd be curious to know what's the use case for this?
