### ISSUE TITLE
The change around `iota_add` -> `iotaD` breaks the compilation of Coquelicot on Coq CI

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#628]
For the record, it seems that the change around `iota_add` -> `iotaD` breaks the compilation of Coquelicot on Coq CI (e.g. [here](https://gitlab.com/coq/coq/-/jobs/822996322)). Something related to `hide` not propagating the scopes of `iota_add`. In particular, `(ssreflect.Deprecation.hide (fun iota_add iotaD => _) iotaD (m - n) n)` interprets `m - n` in the ambiant stack of scopes (thus in `R_scope` in the case of Coquelicot) while it is expected to be interpreted in `nat_scope`.

_Originally posted by @herbelin in https://github.com/math-comp/math-comp/pull/607#issuecomment-720052623_

**Comment by SkySkimmer** [comment]
Should we expect a fix soon or should we stop testing coquelicot in Coq's CI?

**Comment by CohenCyril** [comment]
> Should we expect a fix soon or should we stop testing coquelicot in Coq's CI?

If this is fixable, I expect it to be solve very soon.

**Comment by CohenCyril** [comment]
My attempt miserably failed because Coq's deprecation mechanism works for `Notation` only from Coq 8.11...
I have no clue how to solve the problem detected by Hugo for Coq 8.10 which is still currently supported by mathcomp :cry:

**Comment by CohenCyril** [comment]
@gares any idea on how to solve that?

**Comment by herbelin** [comment]
To add to the discussion, here are a few possible directions I see:
- if the release managers of Coq 8.10 don't mind, the deprecation mechanism of 8.11 is backported to a new release of 8.10
- the `iota_add` change is postponed to a next version of MathComp which has no support for 8.10
- an abbreviation (without deprecation notice) is temporarily used for `iota_add` until the support for 8.10 is abandoned
- this is considered a known bug of the `hide` deprecation mechanism and Coquelicot has to adapt

**Comment by gares** [comment]
We could commit right now `Notation iota_add := iotaD` with no deprecation, and deprecate the old name in 2 releases using Coq's mechanism. After all it's about 2 aliases.

**Comment by CohenCyril** [comment]
OMG, #633 updated `iter_add` instead of `iota_add` :laughing:
