### ISSUE TITLE
make does not work with OPAM-installed OCaml

### ISSUE THREAD

**Issue by jstolarek** [math-comp/math-comp#64]
I am getting build error when compiling Mathematical Components from sources. I got the official 1.6 tarball, extracted it and [here's what I get when I run `make`](https://github.com/math-comp/math-comp/files/455482/ssreflect.txt). You can see that `ocamldep` and `ocamlc` executables are listed as missing. Log clearly shows that they are expected to be in `/usr/bin`. This is not where they are on my system since I have OCaml installation managed by OPAM. The files are definitely on my path:
```
[killy@GLaDOS : ~] which ocamldep
/home/killy/.opam/4.03.0/bin/ocamldep
[killy@GLaDOS : ~] which ocamlc
/home/killy/.opam/4.03.0/bin/ocamlc
```

**Comment by ejgallego** [comment]
Umm, you may want to remove `Makefile.coq` and try again.

**Comment by jstolarek** [comment]
Thanks. Now it works :-)

**Comment by ejgallego** [comment]
NP, anyways, the current makefile seems not right to me, I'll try to get a minute and file a bug report
