### ISSUE TITLE
Meta-issue: dropping support for Coq 8.9

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#644]
A decision should be taken for the next release.
Pros :
- we can address #529 to silence some warnings
- we can consider #599, #501, #502 for merging.
- we could use `under` in mathcomp scripts.

Cons:
- we support "only" 3 released versions of Coq (8.10, 8.11, 8.12) as of 2020-11-12

Relevant PRs and issues are labelled [drops: coq 8.9](https://github.com/math-comp/math-comp/labels/drops%3A%20coq%208.9)

**Comment by chdoc** [comment]
If I'm not mistaken, this would also mean that one can finally make use of the `under` tactic within mathcomp, right?

**Comment by gares** [comment]
we drop it
