### ISSUE TITLE
A generalization of `allrel` that takes two lists

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#662]
```coq
Definition allrel {T S : Type} (r : T -> S -> bool) xs ys :=
   all id [seq r x y | x <- xs, y <- ys].
```
Since `all (fun x => all (fun y => ...) ys) xs` appears at least twice, this generalization would be useful. https://github.com/math-comp/math-comp/blob/676a9266ad77232ab198c86a6a3a3f3f6ba53cc0/mathcomp/ssreflect/path.v#L976-L978 https://github.com/math-comp/math-comp/blob/676a9266ad77232ab198c86a6a3a3f3f6ba53cc0/mathcomp/character/classfun.v#L429-L430

Incidentally, the following ones can be reformulated using the current `allrel`. https://github.com/math-comp/math-comp/blob/676a9266ad77232ab198c86a6a3a3f3f6ba53cc0/mathcomp/field/falgebra.v#L1080-L1082 https://github.com/math-comp/math-comp/blob/676a9266ad77232ab198c86a6a3a3f3f6ba53cc0/mathcomp/field/separable.v#L291-L292

**Comment by CohenCyril** [comment]
Well spotted! Ideally it could be done before the release of 1.12 so that we never have to deprecate `allrel`...Would you have time to do it?

**Comment by pi8027** [comment]
@CohenCyril Will do.

**Comment by CohenCyril** [comment]
Or maybe we can keep the name `allrel` for the one with one argument, as a notation for the new `all2rel` with two arguments?
That way, we are not in a hurry anymore...
