### ISSUE TITLE
wrong deprecation notations in path.v

### ISSUE THREAD

**Issue by chdoc** [math-comp/math-comp#668]
The recently merged PR #650 introduces various deprecation notations. At least one of them causes compatibility issues:

```coq
Notation "@ 'sorted_le_nth'" := (deprecate sorted_le_nth sorted_leq_nth)
  (at level 10, only parsing) : fun_scope.
Notation sorted_le_nth :=
  (fun leT_tr leT_refl x0 s_sorted =>
     @sorted_le_nth _ _ leT_tr leT_refl x0 _ s_sorted _ _) (only parsing).
```
Using  `@sorted_le_nth` (rather than `@sorted_leq_nth`) in the second notation completely messes up the arguments, as can be seen below:
```coq
Lemma foo s (srt_s : sorted leq s) : 
  forall i j, i < j -> i < size s -> j < size s -> nth 0 s i <= nth 0 s j.
Proof.
move => i j /ltnW i_j i_s j_s.
apply: sorted_le_nth. 
(* compare with apply: sorted_leq_nth. *)
```

All of these notations should be carefully rechecked.

Ping! @pi8027 @CohenCyril

**Comment by CohenCyril** [comment]
@pi8027 will you look into it?

**Comment by pi8027** [comment]
Let me fix it.
