### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.13

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#673]
The Coq team is planning to release Coq 8.13-beta1 on December 7, 2020
and Coq 8.13.0 on January 7, 2020.

Your project is currently scheduled for being bundled in the Windows installer.

We are currently testing commit bae9cdb2a12083b8170c3999886839cc1495f969
on branch https://github.com/math-comp/math-comp/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Could you please tag that commit, or communicate us any other tag
that works with the Coq branch v8.13 at the *latest* 15 days before the
date of the final release?

Thanks!
CC: https://github.com/coq/coq/issues/12334

**Comment by gares** [comment]
Can I assume this to be  mathcomp-1.12.0 ?

**Comment by CohenCyril** [comment]
I think so :wink:
