### ISSUE TITLE
Issues with the inheritance from decFieldType to finFieldType

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#689]
- It is done by constructing a decision procedure and thus non-forgetful. Shouldn't we reimplement `DecidableFieldMixin` as a factory? https://github.com/math-comp/math-comp/blob/ee410eb85f36f5e366f807207a7dee8f3e1bdf3a/mathcomp/algebra/finalg.v#L1066-L1082
- `finFieldType` should also inherit from `countDecFieldType` but it does not. (`hierarchy.ml` did not recognize the above inheritance path since its implementation is irregular. I have a fix for this issue.)

**Comment by chdoc** [comment]
>     * I have a fix for this issue.

@pi8027 , can you PR your fix for this issue, so that it can be included in 1.13.0?

**Comment by pi8027** [comment]
@chdoc Yes, see #740.
