### ISSUE TITLE
Uninstallation of SSReflect

### ISSUE THREAD

**Issue by clarus** [math-comp/math-comp#7]
The (empty) folder `lib/coq/user-contrib/mathcomp` is not removed during the uninstallation of the package `coq:mathcomp:ssreflect` : https://coq-bench.github.io/clean/Linux-x86_64-4.02.2-1.2.2/extra-dev/8.5.dev/mathcomp%3Assreflect/dev.html

**Comment by gares** [comment]
I agree, the extra `rm` line should be added to the makefile of the root package (coq:mathcomp:ssreflect) in the dependency graph of opam packages.
