### ISSUE TITLE
"Do not open order_scope" should be documented

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#702]
I saw at least two use cases of order.v that open `order_scope`. I think that the header documentation should strongly recommend users not to open `order_scope` and explain its reason.

**Comment by affeldt-aist** [comment]
Then, shouldn't `order_scope` be renamed `order_scope_for_internal_use` or something similar?
Indeed, as of today, the documentation of `order.v` explicitly mentions that the scope can be opened to access the notations... :-/

**Comment by pi8027** [comment]
If you just want to reason about abstract orders and do not care about any of its concrete instances, it may still make sense to open `order_scope`, although this does not seem to be the case most of the time. So, I oppose the renaming.

**Comment by affeldt-aist** [comment]
Ok, so this PR should be enough to fix the issue: https://github.com/math-comp/math-comp/pull/1104
