### ISSUE TITLE
Attend warning `deprecated-ident-entry`

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#704]
This message shows up regularly with Coq 8.13:
```
Warning: grammar entry "ident" permitted "_" in addition to proper
identifiers; this use is deprecated and its meaning will change in the
future; use "name" instead. [deprecated-ident-entry,deprecated]
```

- PR #706 performs the substitution `ident` -> `name`, but does not work for Coq 8.11 and Coq 8.12 which are still supported by mathcomp at the time this issue was opened.
- PR #707 silences them for the time being.

**Comment by CohenCyril** [comment]
According to [this line of the CI of #706](https://gitlab.com/math-comp/math-comp/-/jobs/1074234129#L351), Coq 8.11 and Coq 8.12 are not ready for the fix. If we want to remain compatible with these two versions of Coq, we will have to silence the warning for a while...
I hope Coq does not suddenly drop the support anytime soon or we will not be able to continue our "three version of Coq support" policy. This might be also the case for #705 (to investigate).

**Comment by proux01** [comment]
This has been fixed by https://github.com/math-comp/math-comp/pull/856
