### ISSUE TITLE
Attend warning `deprecated-hint-without-locality`

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#705]
This message shows up regularly with Coq 8.13:
```
Warning: The default value for hint locality is currently "local" in a
section and "global" otherwise, but is scheduled to change in a future
release. For the time being, adding hints outside of sections without
specifying an explicit locality is therefore deprecated. It is recommended to
use "export" whenever possible. [deprecated-hint-without-locality,deprecated]
```

For now PR #708 just silences the warning, but a longer term solution must be used once Coq 8.11 and Coq 8.12 support is dropped.

**Comment by chdoc** [comment]
For the record, here is some [additional information on Discourse](https://coq.discourse.group/t/change-of-default-locality-for-hint-commands-in-coq-8-13/1140). 

Also, I don't think it is necessary to wait until support for Coq 8.12 is dropped. I have ported [some of my own code](https://github.com/coq-community/graph-theory/commit/004bc78f0e66497c10bca16f7def3873292ae735) to use explicit `#[export]` attributes, and this compiles fine with Coq 8.12.

**Comment by CohenCyril** [comment]
> Also, I don't think it is necessary to wait until support for Coq 8.12 is dropped. I have ported [some of my own code](https://github.com/coq-community/graph-theory/commit/004bc78f0e66497c10bca16f7def3873292ae735) to use explicit `#[export]` attributes, and this compiles fine with Coq 8.12.

Some commands do not support the attribute, that's the problem
