### ISSUE TITLE
contra_neq

### ISSUE THREAD

**Issue by bgregoir** [math-comp/math-comp#74]
The type of contra_neq is too restrictive:
    contra_neq: forall (T : eqType) (x1 y1 x2 y2 : T),
       (x2 = y2 -> x1 = y1) -> x1 != y1 -> x2 != y2
A better type is 
  contra_neq: forall (T1 T2 : eqType) (x1 y1:T1) (x2 y2 : T2),
       (x2 = y2 -> x1 = y1) -> x1 != y1 -> x2 != y2

**Comment by amahboubi** [comment]
Indeed, thanks for the suggestion. Do you have a pull request ready for this? Otherwise I can do it myself later today.

**Comment by bgregoir** [comment]
Thank a lot Assia.
   I think Enrico has already performed the change, next time I will do a pull request.
Benjamin

**Comment by amahboubi** [comment]
Excellent! I close the issue then.
