### ISSUE TITLE
installing MathComp 1.12.0 on Coq 8.13.2 ?

### ISSUE THREAD

**Issue by mechvel** [math-comp/math-comp#758]
I am a newbie for Coq and MathComp. May I ask a newbie question?

I have installed Coq 8.13.2 under Ubuntu Linux 18.04 as a package (not from source),
and it has somehow got into  /snap/, 
so that   coqc  is  recognized as   /snap/bin/coqc.
Then I download  the source of  MathComp 1.12.0  and try to make it from source by applying `make':

> cd  ~/coq/mathComp/1.12.0/mathComp 
> make 

It reports
```
/snap/bin/coq_makefile  -f Make -o Makefile.coq
make -f Makefile.coq --no-print-directory
COQDEP VFILES
... 
Warning: The default value for hint locality is currently "local" in a section and "global" otherwise, 
...
use "export" whenever possible. [deprecated-hint-without-locality,deprecated]
COQC character/character.v
....
COQC ssreflect/ssrmatching.v
```
I thought that it is compiled. Then

  > make install 

reports
```
/snap/bin/coq_makefile  -f Make -o Makefile.coq                                   
make -f Makefile.coq --no-print-directory install                                 
install: cannot delete  '/snap/coq-prover/15/coq-platform/2021-02-1/lib/coq/user-contrib/mathcomp//algebra/all_algebra.vo':
The file system is only for reading                                                                         
...
```
-- many messages of this kind.
May be I need to install one of these two programs into the user area?
How can one somehow configure this?

Thanks.

**Comment by chdoc** [comment]
I have no experience with snap packages under Ubuntu. However, according to [this webpage](https://snapcraft.io/coq-prover) the snap package for coq already includes all the mathcomp packages. From the looks of it, the error message is caused by your install command trying to overwrite the already existing installation of mathcomp inside the snap.

**Comment by mechvel** [comment]
Thank you. 
This indeed looks like an explanation.
I shall see further.
