### ISSUE TITLE
`make` is not idempotent

### ISSUE THREAD

**Issue by RalfJung** [math-comp/math-comp#77]
After running
* `git clean -xfd && git reset --hard HEAD`
* `make && make install`

`git diff` shows
```
diff --git a/mathcomp/ssreflect/Make b/mathcomp/ssreflect/Make
index a10b9c5..993c0a7 100644
--- a/mathcomp/ssreflect/Make
+++ b/mathcomp/ssreflect/Make
@@ -22,3 +22,4 @@ ssreflect.ml4
 
 -I .
 -R . mathcomp.ssreflect
+ssreflect_plugin.mlpack
```

The build process should not modify files that are under version control. This can lead, for example, to strange build failures after upgrades of Coq and/or ssreflect (see #75).

**Comment by ejgallego** [comment]
I also see this bug.

**Comment by gares** [comment]
my bad.  The problem the hack tries to solve is that depending if we are building for version X or Y of Coq we need ssreflect_plugin.mllib or ssreflect_plugin.mlpack ..
ideas are welcome

**Comment by gares** [comment]
funnily enough, the contents of the files are the same... only the name matters, but this is what is stick in `Make`.  Now that I think about it, I did not try to put there both names and see if coq_makefile ignores the wrong one...

**Comment by Barbichu** [comment]
A simple way to solve the problem would be to create Make.tmp as a copy of Make, augmented with the right line, and then call coq_makefile on it.

**Comment by gares** [comment]
IIRC `coq_makefile` merges arguments present in the `Make` file with the ones passed on the command line.  Maybe `coq_makefile -f Make ssreflect_plugin.mllib` is a way to generate a good `Makefile.coq` keeping `Make` untouched.

**Comment by gares** [comment]
This chat Is getting worse than facebook... trying to get this fix done now.

**Comment by gares** [comment]
Tested with 8.6 and 8.4, and pushed.
