### ISSUE TITLE
Informative: pick of tag for upcoming release of Coq Platform for Coq 8.14

### ISSUE THREAD

**Issue by MSoegtropIMC** [math-comp/math-comp#787]
The Coq team released Coq 8.14+rc1 on September 17, 2021
and plans to release Coq 8.14.0 before October 31, 2021.
A corresponding Coq Platform releases should be released before November 30, 2021.
It can be dealyed in case of difficulties until January 31, 2022, but this should be an exception.

This issue is to inform you that your latest tag does work fine with Coq 8.14+rc1.

Coq Platform currently uses the opam package 'coq-mathcomp-ssreflect.1.12.0'
from official repository https://coq.inria.fr/opam/released.

In case this is the version you want to see in Coq Platform, there is nothing to do for you - just close this issue.

In case you would prefer to see an updated version in the upcoming Coq Platform, please inform as as soon as possible!

Thanks!

P.S.: this issue has been created semi-automatically.

CC: https://github.com/coq/platform/issues/139

**Comment by MSoegtropIMC** [comment]
@gares : maybe you can comment on this.

**Comment by CohenCyril** [comment]
Dear @MSoegtropIMC, you can expect the release 1.13.0 of mathcomp to happen within the next month.

**Comment by MSoegtropIMC** [comment]
Dear @CohenCyril : thanks you for the information!

I then will use 1.12.0 in Coq Platform 2021.09 8.14+beta (which will be published soon) and plan to use 1.13.0 in 2021.11 8.14.0 (which is planned for November).

Best regards,

Michael

**Comment by MSoegtropIMC** [comment]
I updated in my (not yet public) working branch these packages for Coq 8.14:
```
coq-mathcomp-ssreflect.1.13.0
coq-mathcomp-fingroup.1.13.0 
coq-mathcomp-algebra.1.13.0
coq-mathcomp-solvable.1.13.0 
coq-mathcomp-field.1.13.0
coq-mathcomp-character.1.13.0
```
Should I update the pick for Coq 8.13.2 in Coq Platform 2021.11 as well?

**Comment by chdoc** [comment]
I would say yes, I don't think there is any reason to stay with 1.12.0 for the 8.13 platform. The 1.13.0 release is compatible with Coq 8.11 to 8.14.

**Comment by MSoegtropIMC** [comment]
Ok, done!
