### ISSUE TITLE
Naming convention for odd_order

### ISSUE THREAD

**Issue by clarus** [math-comp/math-comp#8]
I know this is a detail, but the linter of the bench asks for a `-` instead of a `_` in the name of the package `coq:mathcomp:odd_order`: https://coq-bench.github.io/clean/Linux-x86_64-4.02.2-1.2.2/extra-dev/8.5.dev/mathcomp%3Aodd_order/dev.html

This is for the sake of uniformity, so that the users do not hesitate between a `_`, a `-`, or a big cap letter to separate two words in the name of a package while doing an `opam install`. But if this is too much constraints we could relax the rule.

**Comment by gares** [comment]
Hello Guillaume, I'm afraid that we chose _ because - cannot be used as part of Coq identifiers/logical-paths.

    > Require Import foo-bar.
    >                   ^
    Syntax error: '.' expected after [vernac:gallina_ext] (in [vernac_aux]).

So if the name of the package is also the "namespace" of the Coq theories, your requirement cannot be satisfied.

**Comment by clarus** [comment]
Ok, I do not have strong opinions about it anyway, I was just reporting the results of the bench in a robotic way. I updated the linter so that it accepts the underscores: https://github.com/coq-bench/run/commit/9dc17c649d2d448717ed2cce0e4588684be1645b
