### ISSUE TITLE
Problem when generating documentation

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/math-comp#828]
https://github.com/math-comp/math-comp/blob/ec8eaf48eb1e257ac2024edfb2eed2b96d4b4ec0/etc/utils/builddoc_lib.sh#L18

I observed that this line causes the string `()` to be deleted from the source code; this is a string that we use 
as part of a notation in this [file](https://github.com/math-comp/analysis/blob/master/theories/derive.v) (see line 20 for example).
I have locally replaced it with `s/\(\*{5,}+\)//g` for compilation not to fail but I am not sure this is a fix.
@CohenCyril @gares

**Comment by gares** [comment]
ok, makes sense

**Comment by affeldt-aist** [comment]
Then I'll make a PR, but maybe check first the documentation generated for mathcomp-analysis.
