### ISSUE TITLE
subfilter doesn't exists

### ISSUE THREAD

**Issue by hivert** [math-comp/math-comp#84]
The documentation at the beggining of `seq.v` speak about a `subfilter` function:
```
(* subfilter s : seq sT == when sT has a subType p structure, the sequence    *)
(*                         of items of type sT corresponding to items of s    *)
(*                         for which p holds.                                 *)
```
 I can't find anything like that in the file. Should we simply remove it from the documentation ?

Meta question: Should I ask this here or on the mailing list ?

**Comment by gares** [comment]
linked to issue #89

**Comment by amahboubi** [comment]
Hello @hivert ! This issue has been open for long now... Is it ok if we just merge PR #106 ? Or is there some more documentation needed about how to do that now?

**Comment by hivert** [comment]
Hello @amahboubi ! I'm not sure to understand your question. Are you asking whether you should suggest the user to uses something like `pmap insub` (That's the correct way isn't it) ? If so, I thing simply removing the doc as in #106 is Ok.

**Comment by CohenCyril** [comment]
I agree too, it is done.
