### ISSUE TITLE
Trouble with rewrite and primitive projections

### ISSUE THREAD

**Issue by RalfJung** [math-comp/math-comp#85]
When primitive projections are involved, `rewrite /def` can fail to unfold a definition where `unfold def` works.
The following file demonstrates the issue (thanks @robbertkrebbers for minimizing):
```
Require Import mathcomp.ssreflect.ssreflect.

Set Primitive Projections.

Record foo A := Foo { foo_car : A }.
Arguments foo_car : simpl never.

Definition bar : foo nat := Foo nat 10.

Goal foo_car _ bar = 10.
unfold foo_car. simpl. (* works. Resulting goal: 10 = 10 *)
Restart.
rewrite /foo_car. (* leaves goal unchanged *) 
```

This is using the Coq 8.6 branch (3e6fa1cbdc0ec145728089000595b6ea29f37a4c) and ssreflect master (a4599ba2083ba748dd7a090a4b2eaaa0fc1d295c).

Possibly related: #19

**Comment by RalfJung** [comment]
The pull request has been merged into Coq, but even after upgrading Coq and recompiling ssreflect, the issue as described above persists.

**Comment by gares** [comment]
The (main) bug is in Coq https://coq.inria.fr/bugs/show_bug.cgi?id=5250
I've a work around I'm testing, + some extra code needed in order to properly handle "/primproj", that not being applied in the expression is not recognized as such by ssr code.

**Comment by gares** [comment]
Unfolding should now work (on 8.5, 8.6 and trunk).

**Comment by RalfJung** [comment]
Indeed the testcase works now, thanks!

I can't test the "real thing" right now because some other change in Coq broke some other part of Iris.

**Comment by gares** [comment]
Could you be more explicit?  Did Coq break after 3e6fa1cbdc0ec145728089000595b6ea29f37a4c or it was always failing on the entire Iris?

**Comment by gares** [comment]
Just to know, since we are releasing and all blocking issues have to be reported ASAP.

**Comment by RalfJung** [comment]
Yeah I know you're releasing, I'm in the process of fixing our stuff to be compatible again so I can test stuff.

The failure I was mentioning was due to typeclass inference picking another instance and then rewrite rewriting the wrong thing. Now I'm working on other failures due to `rewrite /def` no longer working if there was a `Global Opaque def` (but `def` is originally `Defined`). Not sure if that's a bug, the interaction of opaqueness and explicit unfolding was always puzzling me,

**Comment by RalfJung** [comment]
> Did Coq break after 3e6fa1cbdc0ec145728089000595b6ea29f37a4c or it was always failing on the entire Iris?

Coq 8.6 + ssreflect master as of a couple days ago worked fine with iris, Coq 8.6 + ssreflect master right now don't. I don't know which commit where broke it, but I think I'll soon have fixed it and then I can point you to the changes we had to make.

**Comment by RalfJung** [comment]
Here's the patch necessary to re-establish compatibility with latest Coq 8.6 and ssreflect master: https://gitlab.mpi-sws.org/FP/iris-coq/commit/f8e2c74ce745f092c4d20e9ef855d7657e25134c

**Comment by gares** [comment]
So you had to add Opaque/Transparent directives... is that for type classes or tactics?

**Comment by RalfJung** [comment]
I can confirm that this bug about `rewrite /def` is also fixed in the instance we had in Iris. However, there seem to be other bug related to ssreflect's `rewrite` and primitive projections, as witnessed by this build failing: <https://gitlab.mpi-sws.org/FP/iris-coq/commit/66c03d6d24c54a64f712d268897df3bb058a4b1c>.
If that's helpful, I can try to minimize this.

(We also have other trouble with primitive projections, but not related to ssreflect, reported as https://coq.inria.fr/bugs/show_bug.cgi?id=5245 )

> So you had to add Opaque/Transparent directives... is that for type classes or tactics?

We generally had the problem of Coq unfolding too many things and hence becoming slow, so we made stuff opaque in various ways. Usually Typeclasses Opaue is enough, I don't know why we do Global Opaque here. @robbertkrebbers do you remember?

**Comment by robbertkrebbers** [comment]
These uses of Opaque have nothing to do with type classes. We were using Opaque directives to avoid `simpl` unfolding these constants.

For example, even when declaring `Arguments incr : simpl never`, the `simpl` tactic would still unfold `of_val incr` because `incr` starts with a constructor. So, we decide to just declare `incr` to be Opaque. That worked, since `rewrite /incr` used to unfold `incr` even when it is Opaque. But apparently that trick no longer works.

This hack is related to https://coq.inria.fr/bugs/show_bug.cgi?id=2986

**Comment by robbertkrebbers** [comment]
Since when does `rewrite /foo` take opacity of `foo` into account?

**Comment by gares** [comment]
Hum, the https://gitlab.mpi-sws.org/FP/iris-coq/commit/66c03d6d24c54a64f712d268897df3bb058a4b1c#18b8279680adf59053090b5c82e20db3f1701856
signals rewrite, and in particular ssrmatching, still need some fix.  In particular the rewrite rule mentions a (I guess) primitive projection as non-applied, while the goal has it applied.  I think I need to add 1 additional case to the filtering: `Const c` should match the "head" of `Proj(c,arg)` by "on the fly" turning it into `App(Const c,[|arg|]`.

**Comment by RalfJung** [comment]
> In particular the rewrite rule mentions a (I guess) primitive projection as non-applied, while the goal has it applied.

Actually I think it's also applied in the rewrite rule, but "less applied". The LHS is `@uPred_or`, which is a `Definition` for a primitive projection applied to a record, but not further applied (it yields a function type): https://gitlab.mpi-sws.org/FP/iris-coq/blob/66c03d6d24c54a64f712d268897df3bb058a4b1c/base_logic/primitive.v#L29

**Comment by RalfJung** [comment]
Oh, I was missing there are actually two types with primitive projections involved: Sealing and uPred. So the sealing primitive projection is applied on the LHS, but then it yields something that is itself of a primitive projection type. So the equality itself is of primitive projection type.

**Comment by RalfJung** [comment]
Here's a minimized example (aka testcase ;-)
```
Require Import mathcomp.ssreflect.ssreflect Coq.Program.Tactics.

Set Primitive Projections.

Inductive seal {A} (f : A) := { unseal : A; seal_eq : unseal = f }.
Arguments unseal {_ _} _.
Arguments seal_eq {_ _} _.

Record uPred : Type := IProp { uPred_holds :> Prop }.

Program Definition uPred_or_def (P Q : uPred) : uPred :=
  {| uPred_holds := P \/ Q |}.
Definition uPred_or_aux : seal (@uPred_or_def). by eexists. Qed.
Definition uPred_or := unseal uPred_or_aux.
Definition uPred_or_eq: @uPred_or = @uPred_or_def := seal_eq uPred_or_aux.

Lemma foobar (P1 P2 Q : uPred) :
  (P1 <-> P2) -> (uPred_or P1 Q) <-> (uPred_or P2 Q).
Proof.
  rewrite uPred_or_eq. (* This fails. *)
  rewrite ->uPred_or_eq. (* This works. *)
```

**Comment by gares** [comment]
Thanks, I'll look into it tomorrow

**Comment by gares** [comment]
See https://github.com/coq/coq/pull/391
I've opened issue #86 and I've pushed a more comprehensive test for primitive projections.
Coq's *rewrite and SSR's one are equally weak wrt un-applied primitive projections.

The fix (for SSR) is too invasive/risky to be pushed now, also I'm not sure we have a lightweight function to know how many arguments a primitive projection has (without re-typing the projected term).

**Comment by RalfJung** [comment]
> See coq/coq#391

Thanks! Coq is now compiling here with this patch, so I can test it on the full development.

> Coq's *rewrite and SSR's one are equally weak wrt un-applied primitive projections.

> I'm not sure we have a lightweight function to know how many arguments a primitive projection has (without re-typing the projected term).

I'm surprised that these are even "a thing"; with projections being the primitive operation on these records, I kind of expected `@proj` to be just sugar for `fun <indices> x => proj x`. But then I also thought primitive projections always have exactly one argument (the record to project from), considering that they don't need the type indices.

**Comment by RalfJung** [comment]
Actually, even the simple testcase above still fails with ssreflect's rewrite and works with Coq's rewrite.
(Or did I screw up and not compile the right thing? I did `opam pin add coq https://github.com/gares/coq.git#80bd0e81305abfc76831ff1c8361e01c4aabb68e`.)

**Comment by gares** [comment]
I've committed `ssrtest/polyproj.v` including your testcase.  I'm pretty sure this one works ;-)

About unapplied primitive projections, they happen to be a special constant that, once unfolded, drops all parameters and applies the primitive projection to the term.  In some sense when you write "proj" or "proj x" the term generated by Coq is very different, i.e. the latter is not in App of the the former to x (that is also the main sort of confusion and source of bugs in the code of Coq and SSR).

**Comment by RalfJung** [comment]
> I've committed ssrtest/polyproj.v including your testcase. I'm pretty sure this one works ;-)

Yeah, sorry for the noise, opam somehow fooled me here. I recompiled again and now the case that used to fail works. Let's see about the rest of Iris ;)

**Comment by RalfJung** [comment]
All right, the branch that used to fail on this issue is now failing on the same issue as the other branch, which is https://coq.inria.fr/bugs/show_bug.cgi?id=5245 . That's not related to ssreflect, so I will close the issue here. Thanks a lot :)
