### ISSUE TITLE
Implicit depends in opam packages

### ISSUE THREAD

**Issue by SnarkBoojum** [math-comp/math-comp#851]
Studying the opam files, I see two lines: character -> field -> solvable -> algebra -> fingroup, and ssreflect (a one-point line).

But if I understand well, all of the first line should depend on ssreflect.

**Comment by proux01** [comment]
They do, the fingroup OPAM file https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mathcomp-fingroup/coq-mathcomp-fingroup.1.14.0/opam reads
```
depends: [ "coq-mathcomp-ssreflect" { = version } ]
```

**Comment by SnarkBoojum** [comment]
How could I miss it?! So that makes a line: character -> field -> solvable -> algebra -> fingroup -> ssreflect.

My report still stands that there should be more depends ; it's strange to split the project into packages and then not really push the process further with fine-grained deps.

**Comment by proux01** [comment]
What do you mean by "more depends"? which "fine-grained deps" would you like to add?

**Comment by SnarkBoojum** [comment]
All cases of direct depend on another package should be explicit ; only indirect depends should be implicit.

In particular, most of them depend directly on ssreflect, and hence should declare it.

**Comment by proux01** [comment]
I see, feel free to open a PR.

**Comment by proux01** [comment]
@SnarkBoojum just to be sure I perfectly understand, we currently have, for instance
* algebra depends on fingroup
* fingroup depends on ssreflect

you advocate to change that to
* algebra depends on fingroup *and ssreflect*
* fingroup depends on ssreflect

so that if one day fingroup stops depending on ssreflect, algebra won't be broken?
Why not but that case seems highly unlikely (and if this ever happens, the problem will remain internal to mathcomp so it should be pretty easy to fix).

**Comment by SnarkBoojum** [comment]
Yes, that's what I advocate.

And as I pointed out already,  it's strange to split the project into packages ; so if you decide to do so, you should do it all the way...

**Comment by chdoc** [comment]
> And as I pointed out already, it's strange to split the project into packages ; so if you decide to do so, you should do it all the way...

I don't think there is anything strange about splitting a large project into multiple packages, because this allows users to only install (and hence check) parts of it. I personally have projects that depend only on `ssreflect` for instance. 

I'm with @proux01 here, that I don't understand what the benefit would be of adding the implicit (or implied) transitive dependencies to other components? Currently the `ssreflect` component specifies the external dependencies (e.g. the compatible versions of `coq`) and every other component simply specifies the components it directly depends on. I'm generally against adding redundant information, as there is a risk that it (accidentally) becomes inconsistent and, as I said initially, I don't see the benefit of doing so.

**Comment by pi8027** [comment]
It would not surprise me if making transitive dependencies explicit (and writing version constraints only on `coq-mathcomp-ssreflect` as some packages do) improve the behavior and performance of the constraint solver of OPAM (e.g., fixes issues like math-comp/algebra-tactics#23), although I didn't have time to check if it is true.

**Comment by SnarkBoojum** [comment]
You're mistaken: I'm not asking for the transitive closure of deps.

I would like **direct** deps to stop being implicit and get explicit.

**Comment by chdoc** [comment]
So what is your definition of a direct dependency? Would you also require that a file in character that happens to use a lemma from the Coq Stdlib (probably doesn't exist) specifies the compatible versions of Coq? Your definition of direct seems to have little to do with the actual dependency graph - once transitive edges are removed you get the same graph.  

Also, you haven't responded to the "why" part of my question? Apart from possibly catering for deficiencies in the OPAM constraint solver (which is so far a wild guess by @pi8027 ) there is no rationale other than "should".

**Comment by pi8027** [comment]
In any case, I think it is worth discussing this issue in the next MathComp meeting and it would be nice to have a clear discipline (supported by clear reasons) on how to write dependencies and constraints of MathComp related OPAM packages.

**Comment by proux01** [comment]
@SnarkBoojum our next meeting is on Wednesday, details are on the wiki: https://github.com/math-comp/math-comp/wiki

**Comment by gares** [comment]
> All cases of direct depend on another package should be explicit

Can you explain why? What would the advantage be?

**Comment by SnarkBoojum** [comment]
The idea is that if A -> B -> C and A -> C are the reals deps and the only explicit one is A -> B, then the day B is rewritten to use D and not depend on C anymore, you break A.

As for the 'why explicit deps?' question, the answer is the same as for the 'why subpackages?' question: I don't understand how you can go for one and not the other...

**Comment by SnarkBoojum** [comment]
@proux01 I'll have a hard time attending the next meeting, as I'll be in front of students 10:00-12:00.

**Comment by proux01** [comment]
Would any next one be better? there is no hurry.

**Comment by proux01** [comment]
> The idea is that if A -> B -> C and A -> C are the reals deps and the only explicit one is A -> B, then the day B is rewritten to use D and not depend on C anymore, you break A.

I generally agree but here, not only this seems unlikely to happen but if that ever happens, the dev of A will know for sure, and update packaging information accordingly, since it will be the very same person as the dev of B making the breaking change.

**Comment by chdoc** [comment]
Moreover, all the packages of mathcomp require their mathcomp dependencies to be exactly the same version as the package itself and the CI tests mathcomp as a whole. So there is never any mathcomp-internal breakage. As I said previously, the reason for the individual packages is solely to allow users to install a subset of the libraries if they don't need the whole library. 

I agree that making direct dependencies explicit is a good idea if those dependencies are developed independently, as one should not rely on an implicit version constraints for libraries that one directly imports. But all of this is of no concern to mathcomp: the ssreflect package will never allow a version of Coq that does not allow compiling the entirety of mathcomp.

**Comment by gares** [comment]
So I believe this bug does not really apply to the core mathcomp packages.

**Comment by SnarkBoojum** [comment]
If you want to allow separate installation of the core mathcomp packages, you need to have correct deps... my point is that there's a contradiction to have one and not the other.

**Comment by proux01** [comment]
Could you explain how the current situation could prevent "separate installation of the core mathcomp packages"?

**Comment by SnarkBoojum** [comment]
It doesn't prevent it, but it doesn't do it right.

**Comment by proux01** [comment]
I understand you are not happy with it, but everybody else (me included) is.
So you'll need stronger arguments than "it doesn't do it right" to convince anyone.

**Comment by SnarkBoojum** [comment]
A surprising stance for people involved in automated proofs and proof-checking, but well...

**Comment by proux01** [comment]
People are just asking for good arguments to do something that would involve an additional maintenance effort.

**Comment by gares** [comment]
We simply don't agree on the axioms :-)

**Comment by SnarkBoojum** [comment]
It's a good practice for resilience when things evolve.

(And you know a practice is good when things go on working when they could have failed.)

**Comment by SnarkBoojum** [comment]
Let us consider at some point a developer (say Jane Doe) creates a very successful project (call it foobar), which uses MC-C, with the following explicit deps: MC-C -> MC-B -> MC-A ; but there's also an implicit MC-C -> MC-A. All in MC 2.71.83.

Many users install foobar, so their package managers install first MC-A, then MC-B, then MC-C and finally foobar. So far so good. And all with the exact same version, of course, all coming from the very same MC 2.71.83.

Here comes MC 3.14.16, where the deps are now MC-C -> MC-D ; and the implicit MC-C -> MC-A is still there. The dep MC-B -> MC-A is still there, too, of course, and explicit, but it's irrelevant.

The foobar users start to update their systems. The package managers all agree on how to do it safely:  install MC-D, update MC-C, update foobar ; finally uninstall MC-B then MC-A since they were only pulled in indirectly. The affected users all agree too: foobar doesn't work anymore. All installed MC-* package use the very same 3.14.16: the package managers did their jobs well.

You might find I'm a bit troublesome with my insistance -- sorry -- but my point is that either MC is monolithic and is always installed as a whole, or it's not, and then deps have to be taken seriously.

There's a good reason why the Debian reference document on packaging has a **whole chapter** on [declaring package relations](https://www.debian.org/doc/debian-policy/ch-relationships.html): no, it's not trivial, and yes getting things wrong can bite your users years after.

**Comment by gares** [comment]
The day we will introce D, we will also update the dependencies as you suggest.

The packages in opam are a hack to lower compilation time. In debian you can safely make one big package, since packages are pre compiled.

**Comment by SnarkBoojum** [comment]
I pushed a split version just yesterday.

And it's more comfortable for users if the packages in the various distributions have similar names: that way a user with distribution foo can watch a video/read a text by someone using distribution bar but still manage to follow with little changes.

**Comment by gares** [comment]
you split matchomp in debian so to have opam like package names? did I get it right?

**Comment by SnarkBoojum** [comment]
Opam is a privileged upstream distribution and I'm following what it does...

**Comment by gares** [comment]
> Opam is a privileged upstream distribution and I'm following what it does...

Why privileged?

As I said, the split is to work around the long time one needs in order to compile full mathcomp when one just needs a few files.
The fact that opam has no binary cache is a serious problem, you don't have that problem is nix or in Debian.
Also note that all packages are called coq-mathcomp-$x, so if you really want to make these names meaningful in Debian, just write `Provides: coq-mathcomp-foo, coq-mathcomp-bar...` as virtual packages.
