### ISSUE TITLE
Suggestion of new lemma polyC_nat for poly.v

### ISSUE THREAD

**Issue by SnarkBoojum** [math-comp/math-comp#884]
While making experiments with polynomials, I needed the following:
```
Variable R: ringType.

Lemma polyC_nat: forall n, polyC n%:R = n%:R :> {poly R}.
Proof.
elim=> [ // | n IHn ].
by rewrite !mulrSr polyCD IHn.
Qed.
```

The reason why I needed it is because evaluating a polynomial is quite trickier than needed:
```
Definition P := 'X^2 - 3%:R * 'X + 2%:R : { poly rat_Ring }.

(* Compute P.[1]. gets stuck: ISSUE or misuse? *)
Lemma P1zero: P.[1] = 0.
Proof.
  unfold P.
  by rewrite !hornerD hornerN !hornerMX -polyC_nat !hornerC hornerX.
Qed.
```

**Comment by SnarkBoojum** [comment]
I worked on polynomials a little more, and it looks like polyC_nat can be avoided ; the problem is that I wanted to work with polynomials and the ring tactic (from MC-algebra-tactics).

As I learned along, I was in three situations:
1. tried to write polynomials with monoms `a *: X^_`, then I couldn't use the ring tactic.
2. wrote them with `a * P` then I needed `polyC_nat` and could use the ring tactic.
3. now I write them the monoms with `*:`, and use `rewrite -!mul_polyC` before using ring ; and indeed I don't use polyC_nat at all.

Perhaps it's more a documentation issue?

**Comment by pi8027** [comment]
@SnarkBoojum Regarding the initial issue, what I suggested was:
```coq
From mathcomp Require Import all_ssreflect all_algebra.

Import GRing.Theory.

Local Open Scope ring_scope.

Lemma polyC_nat (R : ringType) (n : nat) : polyC n%:R = n%:R :> {poly R}.
Proof. by rewrite rmorph_nat. Qed.

Definition P := 'X^2 - 3%:R * 'X + 2%:R : { poly rat }.

Lemma P1zero: P.[1] = 0.
Proof.
rewrite /P !hornerD hornerN !hornerMX.
have ->: 3%:R.[1] = (3%:R)%:P.[1] :> rat by rewrite rmorph_nat. (* Indeed, this is not that nice. *)
by rewrite !hornerC hornerX.
Restart. (* another solution using Algebra Tactics: *)
rewrite /P !hornerE /=; ring.
Qed.
```

Would you mind opening an issue in the Algebra Tactics repo with a small example attached that I can try?

**Comment by pi8027** [comment]
Also, what you needed for "evaluating a polynomial" is probably just `rewrite !hornerE`.

**Comment by proux01** [comment]
I understand the original issue has been fixed, please reopen if I'm wrong.
