### ISSUE TITLE
Missing dependencies for odd_order and real_closed

### ISSUE THREAD

**Issue by clarus** [math-comp/math-comp#9]
It seems that some packages do not compile due to missing dependencies:

* `coq:mathcomp:odd_order`: https://coq-bench.github.io/clean/Linux-x86_64-4.02.2-1.2.2/extra-dev/8.5.dev/mathcomp%3Aodd_order/dev.html
* `coq:mathcomp:real_closed`: https://coq-bench.github.io/clean/Linux-x86_64-4.02.2-1.2.2/extra-dev/8.5.dev/mathcomp%3Areal_closed/dev.html

**Comment by gares** [comment]
I think this bug is no more applicable (eg. the missing dependency on "basic" is not actual, since such package does not exists today)
