### ISSUE TITLE
`coq-mathcomp-ssreflect.1.15.0` fails-to-build-from-source with `coq.dev`

### ISSUE THREAD

**Issue by erikmd** [math-comp/math-comp#921]
Dear mathcomp devs,

You're certainly aware of this already, so just as a heads-up, I open a similar issue w.r.t. [#773](https://github.com/math-comp/math-comp/issues/773) to let you know that I deleted the `mathcomp/mathcomp:1.15.0-coq-dev` docker image which was bitrotting since ~5 days.

Cf. commit [`a57731f`](https://gitlab.com/math-comp/docker-mathcomp/-/commit/a57731f032e5e420c626c97edcf6edc1c8428a70) in `math-comp/docker-mathcomp`.

Cc @CohenCyril @palmskog FYI

FTR, the corresponding error log was:

<details>

```
[ERROR] The compilation of coq-mathcomp-ssreflect.1.15.0 failed at "make -C mathcomp/ssreflect -j 2".
#=== ERROR while compiling coq-mathcomp-ssreflect.1.15.0 ======================#
# context              2.1.3 | linux/x86_64 | ocaml-option-flambda.1 ocaml-variants.4.13.1+options | pinned(https://github.com/math-comp/math-comp/archive/mathcomp-1.15.0.tar.gz)
# path                 ~/.opam/4.13.1+flambda/.opam-switch/build/coq-mathcomp-ssreflect.1.15.0
# command              /usr/bin/make -C mathcomp/ssreflect -j 2
# exit-code            2
# env-file             ~/.opam/log/coq-mathcomp-ssreflect-406-8b841f.env
# output-file          ~/.opam/log/coq-mathcomp-ssreflect-406-8b841f.out
### output ###
# [...]
# and "global" otherwise, but is scheduled to change in a future release. For
# the time being, adding hints outside of sections without specifying an
# explicit locality attribute is therefore deprecated. It is recommended to use
# "export" whenever possible. Use the attributes #[local], #[global] and
# #[export] depending on your choice. For example: "#[export] Hint Unfold foo :
# bar." [deprecated-hint-without-locality,deprecated]
# 
# make[2]: *** [Makefile.coq:793: ssreflect.vo] Error 1
# make[2]: *** Waiting for unfinished jobs....
# make[1]: *** [Makefile.coq:409: all] Error 2
# make: *** [../Makefile.common:99: this-build] Error 2
# make: Leaving directory '/home/coq/.opam/4.13.1+flambda/.opam-switch/build/coq-mathcomp-ssreflect.1.15.0/mathcomp/ssreflect'
```

</details>

**Comment by proux01** [comment]
Thanks @erikmd ! Indeed, 1.15.0 doesn't compile anymore with master. I'm in part the one to blame as I fixed a warning at some point without turning it as error, enabling to reintroduce an unnoticed instance a few days later. Lesson learned: when fixing a warning, keep it as error for some time.

In practice, this means we'll have to relase a 1.16.0 before Coq 8.17 is out. (The good news is that we should also have a 2.0 by then ;-) )
