### ISSUE TITLE
ler_opp2

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/math-comp#933]
https://github.com/math-comp/math-comp/blob/14a9d214dec55f1d0f17c69f37bcfe44a937dda4/mathcomp/algebra/ssrnum.v#L1583

Wouldn't it be more natural to call this lemma `ler_opp`?

**Comment by proux01** [comment]
Indeed

**Comment by CohenCyril** [comment]
Or `lerN`?

**Comment by affeldt-aist** [comment]
> * or `ler_opp`
> * or `lerN2`/`lerN`/`leNr` for the others?

You mean `lerN` for `ler_oppr`? I would see that as an improvement but maybe only because I am bad at left and right. ^_^

But for `lerN2`, I am not sure. In fact, I would argue to keep `ler_opp` because I see `_opp` as the long version of `N`
and also because I am not sure we have been using the `2` notation that much (am I wrong?).

**Comment by proux01** [comment]
There are `ler_add2l` and the like but not sure how "common" it is.

**Comment by affeldt-aist** [comment]
> There are `ler_add2l` and the like but not sure how "common" it is.

Right. But in this case this if the long `_add` instead of `D`.

**Comment by CohenCyril** [comment]
This is for historical reasons
